// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/client/account"
	"github.com/kben/sipgate-rest-api/client/addresses"
	"github.com/kben/sipgate-rest-api/client/app"
	"github.com/kben/sipgate-rest-api/client/authorization"
	"github.com/kben/sipgate-rest-api/client/autorecording"
	"github.com/kben/sipgate-rest-api/client/blacklist"
	"github.com/kben/sipgate-rest-api/client/callrestrictions"
	"github.com/kben/sipgate-rest-api/client/contacts"
	"github.com/kben/sipgate-rest-api/client/devices"
	"github.com/kben/sipgate-rest-api/client/faxlines"
	"github.com/kben/sipgate-rest-api/client/groups"
	"github.com/kben/sipgate-rest-api/client/history"
	"github.com/kben/sipgate-rest-api/client/identity_verification"
	logops "github.com/kben/sipgate-rest-api/client/log"
	"github.com/kben/sipgate-rest-api/client/notifications"
	"github.com/kben/sipgate-rest-api/client/numbers"
	"github.com/kben/sipgate-rest-api/client/phonelines"
	"github.com/kben/sipgate-rest-api/client/ping"
	"github.com/kben/sipgate-rest-api/client/portings"
	"github.com/kben/sipgate-rest-api/client/restrictions"
	"github.com/kben/sipgate-rest-api/client/rtcm"
	"github.com/kben/sipgate-rest-api/client/sessions"
	"github.com/kben/sipgate-rest-api/client/settings"
	"github.com/kben/sipgate-rest-api/client/sms"
	"github.com/kben/sipgate-rest-api/client/urls"
	"github.com/kben/sipgate-rest-api/client/users"
	"github.com/kben/sipgate-rest-api/client/voicemails"
)

// Default sipgate rest HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.sipgate.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new sipgate rest HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SipgateRest {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new sipgate rest HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *SipgateRest {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new sipgate rest client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SipgateRest {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(SipgateRest)
	cli.Transport = transport
	cli.Account = account.New(transport, formats)
	cli.Addresses = addresses.New(transport, formats)
	cli.App = app.New(transport, formats)
	cli.Authorization = authorization.New(transport, formats)
	cli.Autorecording = autorecording.New(transport, formats)
	cli.Blacklist = blacklist.New(transport, formats)
	cli.Callrestrictions = callrestrictions.New(transport, formats)
	cli.Contacts = contacts.New(transport, formats)
	cli.Devices = devices.New(transport, formats)
	cli.Faxlines = faxlines.New(transport, formats)
	cli.Groups = groups.New(transport, formats)
	cli.History = history.New(transport, formats)
	cli.IdentityVerification = identity_verification.New(transport, formats)
	cli.Log = logops.New(transport, formats)
	cli.Notifications = notifications.New(transport, formats)
	cli.Numbers = numbers.New(transport, formats)
	cli.Phonelines = phonelines.New(transport, formats)
	cli.Ping = ping.New(transport, formats)
	cli.Portings = portings.New(transport, formats)
	cli.Restrictions = restrictions.New(transport, formats)
	cli.Rtcm = rtcm.New(transport, formats)
	cli.Sessions = sessions.New(transport, formats)
	cli.Settings = settings.New(transport, formats)
	cli.Sms = sms.New(transport, formats)
	cli.Urls = urls.New(transport, formats)
	cli.Users = users.New(transport, formats)
	cli.Voicemails = voicemails.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// SipgateRest is a client for sipgate rest
type SipgateRest struct {
	Account account.ClientService

	Addresses addresses.ClientService

	App app.ClientService

	Authorization authorization.ClientService

	Autorecording autorecording.ClientService

	Blacklist blacklist.ClientService

	Callrestrictions callrestrictions.ClientService

	Contacts contacts.ClientService

	Devices devices.ClientService

	Faxlines faxlines.ClientService

	Groups groups.ClientService

	History history.ClientService

	IdentityVerification identity_verification.ClientService

	Log logops.ClientService

	Notifications notifications.ClientService

	Numbers numbers.ClientService

	Phonelines phonelines.ClientService

	Ping ping.ClientService

	Portings portings.ClientService

	Restrictions restrictions.ClientService

	Rtcm rtcm.ClientService

	Sessions sessions.ClientService

	Settings settings.ClientService

	Sms sms.ClientService

	Urls urls.ClientService

	Users users.ClientService

	Voicemails voicemails.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SipgateRest) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Account.SetTransport(transport)
	c.Addresses.SetTransport(transport)
	c.App.SetTransport(transport)
	c.Authorization.SetTransport(transport)
	c.Autorecording.SetTransport(transport)
	c.Blacklist.SetTransport(transport)
	c.Callrestrictions.SetTransport(transport)
	c.Contacts.SetTransport(transport)
	c.Devices.SetTransport(transport)
	c.Faxlines.SetTransport(transport)
	c.Groups.SetTransport(transport)
	c.History.SetTransport(transport)
	c.IdentityVerification.SetTransport(transport)
	c.Log.SetTransport(transport)
	c.Notifications.SetTransport(transport)
	c.Numbers.SetTransport(transport)
	c.Phonelines.SetTransport(transport)
	c.Ping.SetTransport(transport)
	c.Portings.SetTransport(transport)
	c.Restrictions.SetTransport(transport)
	c.Rtcm.SetTransport(transport)
	c.Sessions.SetTransport(transport)
	c.Settings.SetTransport(transport)
	c.Sms.SetTransport(transport)
	c.Urls.SetTransport(transport)
	c.Users.SetTransport(transport)
	c.Voicemails.SetTransport(transport)
}
