// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ActivateSimReader is a Reader for the ActivateSim structure.
type ActivateSimReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateSimReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewActivateSimDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewActivateSimDefault creates a ActivateSimDefault with default headers values
func NewActivateSimDefault(code int) *ActivateSimDefault {
	return &ActivateSimDefault{
		_statusCode: code,
	}
}

/*ActivateSimDefault handles this case with default header values.

successful operation
*/
type ActivateSimDefault struct {
	_statusCode int
}

// Code gets the status code for the activate sim default response
func (o *ActivateSimDefault) Code() int {
	return o._statusCode
}

func (o *ActivateSimDefault) Error() string {
	return fmt.Sprintf("[POST /{userId}/devices/{deviceId}/sim][%d] activateSim default ", o._statusCode)
}

func (o *ActivateSimDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
