// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewChangeSingleRowDisplayParams creates a new ChangeSingleRowDisplayParams object
// with the default values initialized.
func NewChangeSingleRowDisplayParams() *ChangeSingleRowDisplayParams {
	var ()
	return &ChangeSingleRowDisplayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeSingleRowDisplayParamsWithTimeout creates a new ChangeSingleRowDisplayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeSingleRowDisplayParamsWithTimeout(timeout time.Duration) *ChangeSingleRowDisplayParams {
	var ()
	return &ChangeSingleRowDisplayParams{

		timeout: timeout,
	}
}

// NewChangeSingleRowDisplayParamsWithContext creates a new ChangeSingleRowDisplayParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeSingleRowDisplayParamsWithContext(ctx context.Context) *ChangeSingleRowDisplayParams {
	var ()
	return &ChangeSingleRowDisplayParams{

		Context: ctx,
	}
}

// NewChangeSingleRowDisplayParamsWithHTTPClient creates a new ChangeSingleRowDisplayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeSingleRowDisplayParamsWithHTTPClient(client *http.Client) *ChangeSingleRowDisplayParams {
	var ()
	return &ChangeSingleRowDisplayParams{
		HTTPClient: client,
	}
}

/*ChangeSingleRowDisplayParams contains all the parameters to send to the API endpoint
for the change single row display operation typically these are written to a http.Request
*/
type ChangeSingleRowDisplayParams struct {

	/*Body*/
	Body *models.SingleRowDisplayRequest
	/*DeviceID
	  The unique device identifier

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change single row display params
func (o *ChangeSingleRowDisplayParams) WithTimeout(timeout time.Duration) *ChangeSingleRowDisplayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change single row display params
func (o *ChangeSingleRowDisplayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change single row display params
func (o *ChangeSingleRowDisplayParams) WithContext(ctx context.Context) *ChangeSingleRowDisplayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change single row display params
func (o *ChangeSingleRowDisplayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change single row display params
func (o *ChangeSingleRowDisplayParams) WithHTTPClient(client *http.Client) *ChangeSingleRowDisplayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change single row display params
func (o *ChangeSingleRowDisplayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change single row display params
func (o *ChangeSingleRowDisplayParams) WithBody(body *models.SingleRowDisplayRequest) *ChangeSingleRowDisplayParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change single row display params
func (o *ChangeSingleRowDisplayParams) SetBody(body *models.SingleRowDisplayRequest) {
	o.Body = body
}

// WithDeviceID adds the deviceID to the change single row display params
func (o *ChangeSingleRowDisplayParams) WithDeviceID(deviceID string) *ChangeSingleRowDisplayParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the change single row display params
func (o *ChangeSingleRowDisplayParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeSingleRowDisplayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
