// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeLocalprefixSettingsReader is a Reader for the ChangeLocalprefixSettings structure.
type ChangeLocalprefixSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeLocalprefixSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewChangeLocalprefixSettingsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewChangeLocalprefixSettingsDefault creates a ChangeLocalprefixSettingsDefault with default headers values
func NewChangeLocalprefixSettingsDefault(code int) *ChangeLocalprefixSettingsDefault {
	return &ChangeLocalprefixSettingsDefault{
		_statusCode: code,
	}
}

/*ChangeLocalprefixSettingsDefault handles this case with default header values.

successful operation
*/
type ChangeLocalprefixSettingsDefault struct {
	_statusCode int
}

// Code gets the status code for the change localprefix settings default response
func (o *ChangeLocalprefixSettingsDefault) Code() int {
	return o._statusCode
}

func (o *ChangeLocalprefixSettingsDefault) Error() string {
	return fmt.Sprintf("[PUT /devices/{deviceId}/localprefix][%d] changeLocalprefixSettings default ", o._statusCode)
}

func (o *ChangeLocalprefixSettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
