// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeSingleRowDisplayReader is a Reader for the ChangeSingleRowDisplay structure.
type ChangeSingleRowDisplayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeSingleRowDisplayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewChangeSingleRowDisplayDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewChangeSingleRowDisplayDefault creates a ChangeSingleRowDisplayDefault with default headers values
func NewChangeSingleRowDisplayDefault(code int) *ChangeSingleRowDisplayDefault {
	return &ChangeSingleRowDisplayDefault{
		_statusCode: code,
	}
}

/*ChangeSingleRowDisplayDefault handles this case with default header values.

successful operation
*/
type ChangeSingleRowDisplayDefault struct {
	_statusCode int
}

// Code gets the status code for the change single row display default response
func (o *ChangeSingleRowDisplayDefault) Code() int {
	return o._statusCode
}

func (o *ChangeSingleRowDisplayDefault) Error() string {
	return fmt.Sprintf("[PUT /devices/{deviceId}/singlerowdisplay][%d] changeSingleRowDisplay default ", o._statusCode)
}

func (o *ChangeSingleRowDisplayDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
