// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangeDevicePasswordParams creates a new ChangeDevicePasswordParams object
// with the default values initialized.
func NewChangeDevicePasswordParams() *ChangeDevicePasswordParams {
	var ()
	return &ChangeDevicePasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeDevicePasswordParamsWithTimeout creates a new ChangeDevicePasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeDevicePasswordParamsWithTimeout(timeout time.Duration) *ChangeDevicePasswordParams {
	var ()
	return &ChangeDevicePasswordParams{

		timeout: timeout,
	}
}

// NewChangeDevicePasswordParamsWithContext creates a new ChangeDevicePasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeDevicePasswordParamsWithContext(ctx context.Context) *ChangeDevicePasswordParams {
	var ()
	return &ChangeDevicePasswordParams{

		Context: ctx,
	}
}

// NewChangeDevicePasswordParamsWithHTTPClient creates a new ChangeDevicePasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeDevicePasswordParamsWithHTTPClient(client *http.Client) *ChangeDevicePasswordParams {
	var ()
	return &ChangeDevicePasswordParams{
		HTTPClient: client,
	}
}

/*ChangeDevicePasswordParams contains all the parameters to send to the API endpoint
for the change device password operation typically these are written to a http.Request
*/
type ChangeDevicePasswordParams struct {

	/*DeviceID
	  The unique device identifier

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change device password params
func (o *ChangeDevicePasswordParams) WithTimeout(timeout time.Duration) *ChangeDevicePasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change device password params
func (o *ChangeDevicePasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change device password params
func (o *ChangeDevicePasswordParams) WithContext(ctx context.Context) *ChangeDevicePasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change device password params
func (o *ChangeDevicePasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change device password params
func (o *ChangeDevicePasswordParams) WithHTTPClient(client *http.Client) *ChangeDevicePasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change device password params
func (o *ChangeDevicePasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the change device password params
func (o *ChangeDevicePasswordParams) WithDeviceID(deviceID string) *ChangeDevicePasswordParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the change device password params
func (o *ChangeDevicePasswordParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeDevicePasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
