// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewChangeTariffAnnouncementParams creates a new ChangeTariffAnnouncementParams object
// with the default values initialized.
func NewChangeTariffAnnouncementParams() *ChangeTariffAnnouncementParams {
	var ()
	return &ChangeTariffAnnouncementParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeTariffAnnouncementParamsWithTimeout creates a new ChangeTariffAnnouncementParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeTariffAnnouncementParamsWithTimeout(timeout time.Duration) *ChangeTariffAnnouncementParams {
	var ()
	return &ChangeTariffAnnouncementParams{

		timeout: timeout,
	}
}

// NewChangeTariffAnnouncementParamsWithContext creates a new ChangeTariffAnnouncementParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeTariffAnnouncementParamsWithContext(ctx context.Context) *ChangeTariffAnnouncementParams {
	var ()
	return &ChangeTariffAnnouncementParams{

		Context: ctx,
	}
}

// NewChangeTariffAnnouncementParamsWithHTTPClient creates a new ChangeTariffAnnouncementParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeTariffAnnouncementParamsWithHTTPClient(client *http.Client) *ChangeTariffAnnouncementParams {
	var ()
	return &ChangeTariffAnnouncementParams{
		HTTPClient: client,
	}
}

/*ChangeTariffAnnouncementParams contains all the parameters to send to the API endpoint
for the change tariff announcement operation typically these are written to a http.Request
*/
type ChangeTariffAnnouncementParams struct {

	/*Body*/
	Body *models.TariffAnnouncementRequest
	/*DeviceID
	  The unique device identifier

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) WithTimeout(timeout time.Duration) *ChangeTariffAnnouncementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) WithContext(ctx context.Context) *ChangeTariffAnnouncementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) WithHTTPClient(client *http.Client) *ChangeTariffAnnouncementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) WithBody(body *models.TariffAnnouncementRequest) *ChangeTariffAnnouncementParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) SetBody(body *models.TariffAnnouncementRequest) {
	o.Body = body
}

// WithDeviceID adds the deviceID to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) WithDeviceID(deviceID string) *ChangeTariffAnnouncementParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the change tariff announcement params
func (o *ChangeTariffAnnouncementParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeTariffAnnouncementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
