// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetTariffAnnouncementReader is a Reader for the GetTariffAnnouncement structure.
type GetTariffAnnouncementReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTariffAnnouncementReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTariffAnnouncementOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetTariffAnnouncementForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTariffAnnouncementOK creates a GetTariffAnnouncementOK with default headers values
func NewGetTariffAnnouncementOK() *GetTariffAnnouncementOK {
	return &GetTariffAnnouncementOK{}
}

/*GetTariffAnnouncementOK handles this case with default header values.

successful operation
*/
type GetTariffAnnouncementOK struct {
	Payload *models.TariffAnnouncementResponse
}

func (o *GetTariffAnnouncementOK) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceId}/tariffannouncement][%d] getTariffAnnouncementOK  %+v", 200, o.Payload)
}

func (o *GetTariffAnnouncementOK) GetPayload() *models.TariffAnnouncementResponse {
	return o.Payload
}

func (o *GetTariffAnnouncementOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TariffAnnouncementResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTariffAnnouncementForbidden creates a GetTariffAnnouncementForbidden with default headers values
func NewGetTariffAnnouncementForbidden() *GetTariffAnnouncementForbidden {
	return &GetTariffAnnouncementForbidden{}
}

/*GetTariffAnnouncementForbidden handles this case with default header values.

Feature not booked
*/
type GetTariffAnnouncementForbidden struct {
}

func (o *GetTariffAnnouncementForbidden) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceId}/tariffannouncement][%d] getTariffAnnouncementForbidden ", 403)
}

func (o *GetTariffAnnouncementForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
