// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetCallerIDReader is a Reader for the GetCallerID structure.
type GetCallerIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCallerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCallerIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetCallerIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCallerIDOK creates a GetCallerIDOK with default headers values
func NewGetCallerIDOK() *GetCallerIDOK {
	return &GetCallerIDOK{}
}

/*GetCallerIDOK handles this case with default header values.

successful operation
*/
type GetCallerIDOK struct {
	Payload *models.CallerIDResponse
}

func (o *GetCallerIDOK) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceId}/callerid][%d] getCallerIdOK  %+v", 200, o.Payload)
}

func (o *GetCallerIDOK) GetPayload() *models.CallerIDResponse {
	return o.Payload
}

func (o *GetCallerIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CallerIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCallerIDForbidden creates a GetCallerIDForbidden with default headers values
func NewGetCallerIDForbidden() *GetCallerIDForbidden {
	return &GetCallerIDForbidden{}
}

/*GetCallerIDForbidden handles this case with default header values.

Feature not booked
*/
type GetCallerIDForbidden struct {
}

func (o *GetCallerIDForbidden) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceId}/callerid][%d] getCallerIdForbidden ", 403)
}

func (o *GetCallerIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
