// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLocalprefixParams creates a new GetLocalprefixParams object
// with the default values initialized.
func NewGetLocalprefixParams() *GetLocalprefixParams {
	var ()
	return &GetLocalprefixParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLocalprefixParamsWithTimeout creates a new GetLocalprefixParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLocalprefixParamsWithTimeout(timeout time.Duration) *GetLocalprefixParams {
	var ()
	return &GetLocalprefixParams{

		timeout: timeout,
	}
}

// NewGetLocalprefixParamsWithContext creates a new GetLocalprefixParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLocalprefixParamsWithContext(ctx context.Context) *GetLocalprefixParams {
	var ()
	return &GetLocalprefixParams{

		Context: ctx,
	}
}

// NewGetLocalprefixParamsWithHTTPClient creates a new GetLocalprefixParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLocalprefixParamsWithHTTPClient(client *http.Client) *GetLocalprefixParams {
	var ()
	return &GetLocalprefixParams{
		HTTPClient: client,
	}
}

/*GetLocalprefixParams contains all the parameters to send to the API endpoint
for the get localprefix operation typically these are written to a http.Request
*/
type GetLocalprefixParams struct {

	/*DeviceID
	  The unique device identifier

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get localprefix params
func (o *GetLocalprefixParams) WithTimeout(timeout time.Duration) *GetLocalprefixParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get localprefix params
func (o *GetLocalprefixParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get localprefix params
func (o *GetLocalprefixParams) WithContext(ctx context.Context) *GetLocalprefixParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get localprefix params
func (o *GetLocalprefixParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get localprefix params
func (o *GetLocalprefixParams) WithHTTPClient(client *http.Client) *GetLocalprefixParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get localprefix params
func (o *GetLocalprefixParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the get localprefix params
func (o *GetLocalprefixParams) WithDeviceID(deviceID string) *GetLocalprefixParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get localprefix params
func (o *GetLocalprefixParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLocalprefixParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
