// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteHistoryEntriesParams creates a new DeleteHistoryEntriesParams object
// with the default values initialized.
func NewDeleteHistoryEntriesParams() *DeleteHistoryEntriesParams {
	var ()
	return &DeleteHistoryEntriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHistoryEntriesParamsWithTimeout creates a new DeleteHistoryEntriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteHistoryEntriesParamsWithTimeout(timeout time.Duration) *DeleteHistoryEntriesParams {
	var ()
	return &DeleteHistoryEntriesParams{

		timeout: timeout,
	}
}

// NewDeleteHistoryEntriesParamsWithContext creates a new DeleteHistoryEntriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteHistoryEntriesParamsWithContext(ctx context.Context) *DeleteHistoryEntriesParams {
	var ()
	return &DeleteHistoryEntriesParams{

		Context: ctx,
	}
}

// NewDeleteHistoryEntriesParamsWithHTTPClient creates a new DeleteHistoryEntriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteHistoryEntriesParamsWithHTTPClient(client *http.Client) *DeleteHistoryEntriesParams {
	var ()
	return &DeleteHistoryEntriesParams{
		HTTPClient: client,
	}
}

/*DeleteHistoryEntriesParams contains all the parameters to send to the API endpoint
for the delete history entries operation typically these are written to a http.Request
*/
type DeleteHistoryEntriesParams struct {

	/*ID
	  List of entry ids to delete

	*/
	ID []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete history entries params
func (o *DeleteHistoryEntriesParams) WithTimeout(timeout time.Duration) *DeleteHistoryEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete history entries params
func (o *DeleteHistoryEntriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete history entries params
func (o *DeleteHistoryEntriesParams) WithContext(ctx context.Context) *DeleteHistoryEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete history entries params
func (o *DeleteHistoryEntriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete history entries params
func (o *DeleteHistoryEntriesParams) WithHTTPClient(client *http.Client) *DeleteHistoryEntriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete history entries params
func (o *DeleteHistoryEntriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete history entries params
func (o *DeleteHistoryEntriesParams) WithID(id []string) *DeleteHistoryEntriesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete history entries params
func (o *DeleteHistoryEntriesParams) SetID(id []string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHistoryEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesID := o.ID

	joinedID := swag.JoinByFormat(valuesID, "multi")
	// query array param id
	if err := r.SetQueryParam("id", joinedID...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
