// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteHistoryEntryReader is a Reader for the DeleteHistoryEntry structure.
type DeleteHistoryEntryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHistoryEntryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteHistoryEntryDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteHistoryEntryDefault creates a DeleteHistoryEntryDefault with default headers values
func NewDeleteHistoryEntryDefault(code int) *DeleteHistoryEntryDefault {
	return &DeleteHistoryEntryDefault{
		_statusCode: code,
	}
}

/*DeleteHistoryEntryDefault handles this case with default header values.

successful operation
*/
type DeleteHistoryEntryDefault struct {
	_statusCode int
}

// Code gets the status code for the delete history entry default response
func (o *DeleteHistoryEntryDefault) Code() int {
	return o._statusCode
}

func (o *DeleteHistoryEntryDefault) Error() string {
	return fmt.Sprintf("[DELETE /history/{entryId}][%d] deleteHistoryEntry default ", o._statusCode)
}

func (o *DeleteHistoryEntryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
