// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetHistoryCSVReader is a Reader for the GetHistoryCSV structure.
type GetHistoryCSVReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHistoryCSVReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHistoryCSVOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHistoryCSVOK creates a GetHistoryCSVOK with default headers values
func NewGetHistoryCSVOK() *GetHistoryCSVOK {
	return &GetHistoryCSVOK{}
}

/*GetHistoryCSVOK handles this case with default header values.

successful operation
*/
type GetHistoryCSVOK struct {
	Payload *models.HistoryResponse
}

func (o *GetHistoryCSVOK) Error() string {
	return fmt.Sprintf("[GET /history/export][%d] getHistoryCSVOK  %+v", 200, o.Payload)
}

func (o *GetHistoryCSVOK) GetPayload() *models.HistoryResponse {
	return o.Payload
}

func (o *GetHistoryCSVOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
