// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewSetArchiveParams creates a new SetArchiveParams object
// with the default values initialized.
func NewSetArchiveParams() *SetArchiveParams {
	var ()
	return &SetArchiveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetArchiveParamsWithTimeout creates a new SetArchiveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetArchiveParamsWithTimeout(timeout time.Duration) *SetArchiveParams {
	var ()
	return &SetArchiveParams{

		timeout: timeout,
	}
}

// NewSetArchiveParamsWithContext creates a new SetArchiveParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetArchiveParamsWithContext(ctx context.Context) *SetArchiveParams {
	var ()
	return &SetArchiveParams{

		Context: ctx,
	}
}

// NewSetArchiveParamsWithHTTPClient creates a new SetArchiveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetArchiveParamsWithHTTPClient(client *http.Client) *SetArchiveParams {
	var ()
	return &SetArchiveParams{
		HTTPClient: client,
	}
}

/*SetArchiveParams contains all the parameters to send to the API endpoint
for the set archive operation typically these are written to a http.Request
*/
type SetArchiveParams struct {

	/*Body*/
	Body *models.SetHistoryEntryArchiveRequest
	/*EntryID
	  The unique call, fax, sms or voicemail identifier

	*/
	EntryID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set archive params
func (o *SetArchiveParams) WithTimeout(timeout time.Duration) *SetArchiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set archive params
func (o *SetArchiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set archive params
func (o *SetArchiveParams) WithContext(ctx context.Context) *SetArchiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set archive params
func (o *SetArchiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set archive params
func (o *SetArchiveParams) WithHTTPClient(client *http.Client) *SetArchiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set archive params
func (o *SetArchiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set archive params
func (o *SetArchiveParams) WithBody(body *models.SetHistoryEntryArchiveRequest) *SetArchiveParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set archive params
func (o *SetArchiveParams) SetBody(body *models.SetHistoryEntryArchiveRequest) {
	o.Body = body
}

// WithEntryID adds the entryID to the set archive params
func (o *SetArchiveParams) WithEntryID(entryID string) *SetArchiveParams {
	o.SetEntryID(entryID)
	return o
}

// SetEntryID adds the entryId to the set archive params
func (o *SetArchiveParams) SetEntryID(entryID string) {
	o.EntryID = entryID
}

// WriteToRequest writes these params to a swagger request
func (o *SetArchiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param entryId
	if err := r.SetPathParam("entryId", o.EntryID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
