// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetArchiveReader is a Reader for the SetArchive structure.
type SetArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewSetArchiveDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewSetArchiveDefault creates a SetArchiveDefault with default headers values
func NewSetArchiveDefault(code int) *SetArchiveDefault {
	return &SetArchiveDefault{
		_statusCode: code,
	}
}

/*SetArchiveDefault handles this case with default header values.

successful operation
*/
type SetArchiveDefault struct {
	_statusCode int
}

// Code gets the status code for the set archive default response
func (o *SetArchiveDefault) Code() int {
	return o._statusCode
}

func (o *SetArchiveDefault) Error() string {
	return fmt.Sprintf("[PUT /history/{entryId}/archive][%d] setArchive default ", o._statusCode)
}

func (o *SetArchiveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
