// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewUpdateHistoryEntriesParams creates a new UpdateHistoryEntriesParams object
// with the default values initialized.
func NewUpdateHistoryEntriesParams() *UpdateHistoryEntriesParams {
	var ()
	return &UpdateHistoryEntriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateHistoryEntriesParamsWithTimeout creates a new UpdateHistoryEntriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateHistoryEntriesParamsWithTimeout(timeout time.Duration) *UpdateHistoryEntriesParams {
	var ()
	return &UpdateHistoryEntriesParams{

		timeout: timeout,
	}
}

// NewUpdateHistoryEntriesParamsWithContext creates a new UpdateHistoryEntriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateHistoryEntriesParamsWithContext(ctx context.Context) *UpdateHistoryEntriesParams {
	var ()
	return &UpdateHistoryEntriesParams{

		Context: ctx,
	}
}

// NewUpdateHistoryEntriesParamsWithHTTPClient creates a new UpdateHistoryEntriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateHistoryEntriesParamsWithHTTPClient(client *http.Client) *UpdateHistoryEntriesParams {
	var ()
	return &UpdateHistoryEntriesParams{
		HTTPClient: client,
	}
}

/*UpdateHistoryEntriesParams contains all the parameters to send to the API endpoint
for the update history entries operation typically these are written to a http.Request
*/
type UpdateHistoryEntriesParams struct {

	/*Body
	  A list of events which should be updated. Must be less than 150

	*/
	Body []*models.UpdateHistoryEntriesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update history entries params
func (o *UpdateHistoryEntriesParams) WithTimeout(timeout time.Duration) *UpdateHistoryEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update history entries params
func (o *UpdateHistoryEntriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update history entries params
func (o *UpdateHistoryEntriesParams) WithContext(ctx context.Context) *UpdateHistoryEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update history entries params
func (o *UpdateHistoryEntriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update history entries params
func (o *UpdateHistoryEntriesParams) WithHTTPClient(client *http.Client) *UpdateHistoryEntriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update history entries params
func (o *UpdateHistoryEntriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update history entries params
func (o *UpdateHistoryEntriesParams) WithBody(body []*models.UpdateHistoryEntriesRequest) *UpdateHistoryEntriesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update history entries params
func (o *UpdateHistoryEntriesParams) SetBody(body []*models.UpdateHistoryEntriesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateHistoryEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
