// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewAddSmsEmailNotificationParams creates a new AddSmsEmailNotificationParams object
// with the default values initialized.
func NewAddSmsEmailNotificationParams() *AddSmsEmailNotificationParams {
	var ()
	return &AddSmsEmailNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddSmsEmailNotificationParamsWithTimeout creates a new AddSmsEmailNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddSmsEmailNotificationParamsWithTimeout(timeout time.Duration) *AddSmsEmailNotificationParams {
	var ()
	return &AddSmsEmailNotificationParams{

		timeout: timeout,
	}
}

// NewAddSmsEmailNotificationParamsWithContext creates a new AddSmsEmailNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddSmsEmailNotificationParamsWithContext(ctx context.Context) *AddSmsEmailNotificationParams {
	var ()
	return &AddSmsEmailNotificationParams{

		Context: ctx,
	}
}

// NewAddSmsEmailNotificationParamsWithHTTPClient creates a new AddSmsEmailNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddSmsEmailNotificationParamsWithHTTPClient(client *http.Client) *AddSmsEmailNotificationParams {
	var ()
	return &AddSmsEmailNotificationParams{
		HTTPClient: client,
	}
}

/*AddSmsEmailNotificationParams contains all the parameters to send to the API endpoint
for the add sms email notification operation typically these are written to a http.Request
*/
type AddSmsEmailNotificationParams struct {

	/*Body*/
	Body *models.AddSmsEmailNotificationRequest
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add sms email notification params
func (o *AddSmsEmailNotificationParams) WithTimeout(timeout time.Duration) *AddSmsEmailNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add sms email notification params
func (o *AddSmsEmailNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add sms email notification params
func (o *AddSmsEmailNotificationParams) WithContext(ctx context.Context) *AddSmsEmailNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add sms email notification params
func (o *AddSmsEmailNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add sms email notification params
func (o *AddSmsEmailNotificationParams) WithHTTPClient(client *http.Client) *AddSmsEmailNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add sms email notification params
func (o *AddSmsEmailNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add sms email notification params
func (o *AddSmsEmailNotificationParams) WithBody(body *models.AddSmsEmailNotificationRequest) *AddSmsEmailNotificationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add sms email notification params
func (o *AddSmsEmailNotificationParams) SetBody(body *models.AddSmsEmailNotificationRequest) {
	o.Body = body
}

// WithUserID adds the userID to the add sms email notification params
func (o *AddSmsEmailNotificationParams) WithUserID(userID string) *AddSmsEmailNotificationParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the add sms email notification params
func (o *AddSmsEmailNotificationParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *AddSmsEmailNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
