// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewAddFaxEmailNotificationParams creates a new AddFaxEmailNotificationParams object
// with the default values initialized.
func NewAddFaxEmailNotificationParams() *AddFaxEmailNotificationParams {
	var ()
	return &AddFaxEmailNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddFaxEmailNotificationParamsWithTimeout creates a new AddFaxEmailNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddFaxEmailNotificationParamsWithTimeout(timeout time.Duration) *AddFaxEmailNotificationParams {
	var ()
	return &AddFaxEmailNotificationParams{

		timeout: timeout,
	}
}

// NewAddFaxEmailNotificationParamsWithContext creates a new AddFaxEmailNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddFaxEmailNotificationParamsWithContext(ctx context.Context) *AddFaxEmailNotificationParams {
	var ()
	return &AddFaxEmailNotificationParams{

		Context: ctx,
	}
}

// NewAddFaxEmailNotificationParamsWithHTTPClient creates a new AddFaxEmailNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddFaxEmailNotificationParamsWithHTTPClient(client *http.Client) *AddFaxEmailNotificationParams {
	var ()
	return &AddFaxEmailNotificationParams{
		HTTPClient: client,
	}
}

/*AddFaxEmailNotificationParams contains all the parameters to send to the API endpoint
for the add fax email notification operation typically these are written to a http.Request
*/
type AddFaxEmailNotificationParams struct {

	/*Body*/
	Body *models.AddFaxEmailNotificationRequest
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add fax email notification params
func (o *AddFaxEmailNotificationParams) WithTimeout(timeout time.Duration) *AddFaxEmailNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add fax email notification params
func (o *AddFaxEmailNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add fax email notification params
func (o *AddFaxEmailNotificationParams) WithContext(ctx context.Context) *AddFaxEmailNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add fax email notification params
func (o *AddFaxEmailNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add fax email notification params
func (o *AddFaxEmailNotificationParams) WithHTTPClient(client *http.Client) *AddFaxEmailNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add fax email notification params
func (o *AddFaxEmailNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add fax email notification params
func (o *AddFaxEmailNotificationParams) WithBody(body *models.AddFaxEmailNotificationRequest) *AddFaxEmailNotificationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add fax email notification params
func (o *AddFaxEmailNotificationParams) SetBody(body *models.AddFaxEmailNotificationRequest) {
	o.Body = body
}

// WithUserID adds the userID to the add fax email notification params
func (o *AddFaxEmailNotificationParams) WithUserID(userID string) *AddFaxEmailNotificationParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the add fax email notification params
func (o *AddFaxEmailNotificationParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *AddFaxEmailNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
