// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateEmailNotificationForCallReader is a Reader for the CreateEmailNotificationForCall structure.
type CreateEmailNotificationForCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEmailNotificationForCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 403:
		result := NewCreateEmailNotificationForCallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateEmailNotificationForCallForbidden creates a CreateEmailNotificationForCallForbidden with default headers values
func NewCreateEmailNotificationForCallForbidden() *CreateEmailNotificationForCallForbidden {
	return &CreateEmailNotificationForCallForbidden{}
}

/*CreateEmailNotificationForCallForbidden handles this case with default header values.

Limit reached
*/
type CreateEmailNotificationForCallForbidden struct {
}

func (o *CreateEmailNotificationForCallForbidden) Error() string {
	return fmt.Sprintf("[POST /{userId}/notifications/call/email][%d] createEmailNotificationForCallForbidden ", 403)
}

func (o *CreateEmailNotificationForCallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
