// Code generated by go-swagger; DO NOT EDIT.

package callrestrictions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// SetCallRestrictionReader is a Reader for the SetCallRestriction structure.
type SetCallRestrictionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetCallRestrictionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetCallRestrictionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSetCallRestrictionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetCallRestrictionOK creates a SetCallRestrictionOK with default headers values
func NewSetCallRestrictionOK() *SetCallRestrictionOK {
	return &SetCallRestrictionOK{}
}

/*SetCallRestrictionOK handles this case with default header values.

successful operation
*/
type SetCallRestrictionOK struct {
	Payload *models.CallRestrictionResponse
}

func (o *SetCallRestrictionOK) Error() string {
	return fmt.Sprintf("[POST /{userId}/callrestrictions/{restriction}][%d] setCallRestrictionOK  %+v", 200, o.Payload)
}

func (o *SetCallRestrictionOK) GetPayload() *models.CallRestrictionResponse {
	return o.Payload
}

func (o *SetCallRestrictionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CallRestrictionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetCallRestrictionNotFound creates a SetCallRestrictionNotFound with default headers values
func NewSetCallRestrictionNotFound() *SetCallRestrictionNotFound {
	return &SetCallRestrictionNotFound{}
}

/*SetCallRestrictionNotFound handles this case with default header values.

Call restriction not found
*/
type SetCallRestrictionNotFound struct {
}

func (o *SetCallRestrictionNotFound) Error() string {
	return fmt.Sprintf("[POST /{userId}/callrestrictions/{restriction}][%d] setCallRestrictionNotFound ", 404)
}

func (o *SetCallRestrictionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
