// Code generated by go-swagger; DO NOT EDIT.

package numbers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeQuickDialNumberReader is a Reader for the ChangeQuickDialNumber structure.
type ChangeQuickDialNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeQuickDialNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewChangeQuickDialNumberDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewChangeQuickDialNumberDefault creates a ChangeQuickDialNumberDefault with default headers values
func NewChangeQuickDialNumberDefault(code int) *ChangeQuickDialNumberDefault {
	return &ChangeQuickDialNumberDefault{
		_statusCode: code,
	}
}

/*ChangeQuickDialNumberDefault handles this case with default header values.

successful operation
*/
type ChangeQuickDialNumberDefault struct {
	_statusCode int
}

// Code gets the status code for the change quick dial number default response
func (o *ChangeQuickDialNumberDefault) Code() int {
	return o._statusCode
}

func (o *ChangeQuickDialNumberDefault) Error() string {
	return fmt.Sprintf("[PUT /numbers/quickdial/{quickdialId}][%d] changeQuickDialNumber default ", o._statusCode)
}

func (o *ChangeQuickDialNumberDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
