// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewNewRecordingParams creates a new NewRecordingParams object
// with the default values initialized.
func NewNewRecordingParams() *NewRecordingParams {
	var ()
	return &NewRecordingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNewRecordingParamsWithTimeout creates a new NewRecordingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNewRecordingParamsWithTimeout(timeout time.Duration) *NewRecordingParams {
	var ()
	return &NewRecordingParams{

		timeout: timeout,
	}
}

// NewNewRecordingParamsWithContext creates a new NewRecordingParams object
// with the default values initialized, and the ability to set a context for a request
func NewNewRecordingParamsWithContext(ctx context.Context) *NewRecordingParams {
	var ()
	return &NewRecordingParams{

		Context: ctx,
	}
}

// NewNewRecordingParamsWithHTTPClient creates a new NewRecordingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNewRecordingParamsWithHTTPClient(client *http.Client) *NewRecordingParams {
	var ()
	return &NewRecordingParams{
		HTTPClient: client,
	}
}

/*NewRecordingParams contains all the parameters to send to the API endpoint
for the new recording operation typically these are written to a http.Request
*/
type NewRecordingParams struct {

	/*Body*/
	Body *models.NewVoicemailRecordingRecordingRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the new recording params
func (o *NewRecordingParams) WithTimeout(timeout time.Duration) *NewRecordingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new recording params
func (o *NewRecordingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new recording params
func (o *NewRecordingParams) WithContext(ctx context.Context) *NewRecordingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new recording params
func (o *NewRecordingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new recording params
func (o *NewRecordingParams) WithHTTPClient(client *http.Client) *NewRecordingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new recording params
func (o *NewRecordingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the new recording params
func (o *NewRecordingParams) WithBody(body *models.NewVoicemailRecordingRecordingRequest) *NewRecordingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the new recording params
func (o *NewRecordingParams) SetBody(body *models.NewVoicemailRecordingRecordingRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NewRecordingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
