// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewPlayRecordingParams creates a new PlayRecordingParams object
// with the default values initialized.
func NewPlayRecordingParams() *PlayRecordingParams {
	var ()
	return &PlayRecordingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPlayRecordingParamsWithTimeout creates a new PlayRecordingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPlayRecordingParamsWithTimeout(timeout time.Duration) *PlayRecordingParams {
	var ()
	return &PlayRecordingParams{

		timeout: timeout,
	}
}

// NewPlayRecordingParamsWithContext creates a new PlayRecordingParams object
// with the default values initialized, and the ability to set a context for a request
func NewPlayRecordingParamsWithContext(ctx context.Context) *PlayRecordingParams {
	var ()
	return &PlayRecordingParams{

		Context: ctx,
	}
}

// NewPlayRecordingParamsWithHTTPClient creates a new PlayRecordingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPlayRecordingParamsWithHTTPClient(client *http.Client) *PlayRecordingParams {
	var ()
	return &PlayRecordingParams{
		HTTPClient: client,
	}
}

/*PlayRecordingParams contains all the parameters to send to the API endpoint
for the play recording operation typically these are written to a http.Request
*/
type PlayRecordingParams struct {

	/*Body*/
	Body *models.PlayRecordingRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the play recording params
func (o *PlayRecordingParams) WithTimeout(timeout time.Duration) *PlayRecordingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the play recording params
func (o *PlayRecordingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the play recording params
func (o *PlayRecordingParams) WithContext(ctx context.Context) *PlayRecordingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the play recording params
func (o *PlayRecordingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the play recording params
func (o *PlayRecordingParams) WithHTTPClient(client *http.Client) *PlayRecordingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the play recording params
func (o *PlayRecordingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the play recording params
func (o *PlayRecordingParams) WithBody(body *models.PlayRecordingRequest) *PlayRecordingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the play recording params
func (o *PlayRecordingParams) SetBody(body *models.PlayRecordingRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PlayRecordingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
