// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateClientParams creates a new UpdateClientParams object
// with the default values initialized.
func NewUpdateClientParams() *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateClientParamsWithTimeout creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateClientParamsWithTimeout(timeout time.Duration) *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		timeout: timeout,
	}
}

// NewUpdateClientParamsWithContext creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateClientParamsWithContext(ctx context.Context) *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		Context: ctx,
	}
}

// NewUpdateClientParamsWithHTTPClient creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateClientParamsWithHTTPClient(client *http.Client) *UpdateClientParams {
	var ()
	return &UpdateClientParams{
		HTTPClient: client,
	}
}

/*UpdateClientParams contains all the parameters to send to the API endpoint
for the update client operation typically these are written to a http.Request
*/
type UpdateClientParams struct {

	/*Client*/
	Client UpdateClientBody
	/*ClientID
	  The unique OAuth 2.0 client identifier

	*/
	ClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update client params
func (o *UpdateClientParams) WithTimeout(timeout time.Duration) *UpdateClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update client params
func (o *UpdateClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update client params
func (o *UpdateClientParams) WithContext(ctx context.Context) *UpdateClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update client params
func (o *UpdateClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update client params
func (o *UpdateClientParams) WithHTTPClient(client *http.Client) *UpdateClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update client params
func (o *UpdateClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClient adds the client to the update client params
func (o *UpdateClientParams) WithClient(client UpdateClientBody) *UpdateClientParams {
	o.SetClient(client)
	return o
}

// SetClient adds the client to the update client params
func (o *UpdateClientParams) SetClient(client UpdateClientBody) {
	o.Client = client
}

// WithClientID adds the clientID to the update client params
func (o *UpdateClientParams) WithClientID(clientID string) *UpdateClientParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the update client params
func (o *UpdateClientParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Client); err != nil {
		return err
	}

	// path param clientId
	if err := r.SetPathParam("clientId", o.ClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
