// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteContactReader is a Reader for the DeleteContact structure.
type DeleteContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteContactDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteContactDefault creates a DeleteContactDefault with default headers values
func NewDeleteContactDefault(code int) *DeleteContactDefault {
	return &DeleteContactDefault{
		_statusCode: code,
	}
}

/*DeleteContactDefault handles this case with default header values.

successful operation
*/
type DeleteContactDefault struct {
	_statusCode int
}

// Code gets the status code for the delete contact default response
func (o *DeleteContactDefault) Code() int {
	return o._statusCode
}

func (o *DeleteContactDefault) Error() string {
	return fmt.Sprintf("[DELETE /contacts/{contactid}][%d] deleteContact default ", o._statusCode)
}

func (o *DeleteContactDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
