// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetAllContactsReader is a Reader for the GetAllContacts structure.
type GetAllContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllContactsOK creates a GetAllContactsOK with default headers values
func NewGetAllContactsOK() *GetAllContactsOK {
	return &GetAllContactsOK{}
}

/*GetAllContactsOK handles this case with default header values.

successful operation
*/
type GetAllContactsOK struct {
	Payload *models.InternalContactsResponse
}

func (o *GetAllContactsOK) Error() string {
	return fmt.Sprintf("[GET /contacts/internal][%d] getAllContactsOK  %+v", 200, o.Payload)
}

func (o *GetAllContactsOK) GetPayload() *models.InternalContactsResponse {
	return o.Payload
}

func (o *GetAllContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalContactsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
