// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateContactReader is a Reader for the UpdateContact structure.
type UpdateContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewUpdateContactDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewUpdateContactDefault creates a UpdateContactDefault with default headers values
func NewUpdateContactDefault(code int) *UpdateContactDefault {
	return &UpdateContactDefault{
		_statusCode: code,
	}
}

/*UpdateContactDefault handles this case with default header values.

successful operation
*/
type UpdateContactDefault struct {
	_statusCode int
}

// Code gets the status code for the update contact default response
func (o *UpdateContactDefault) Code() int {
	return o._statusCode
}

func (o *UpdateContactDefault) Error() string {
	return fmt.Sprintf("[PUT /contacts/{contactId}][%d] updateContact default ", o._statusCode)
}

func (o *UpdateContactDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
