// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewUpdateContactParams creates a new UpdateContactParams object
// with the default values initialized.
func NewUpdateContactParams() *UpdateContactParams {
	var ()
	return &UpdateContactParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateContactParamsWithTimeout creates a new UpdateContactParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateContactParamsWithTimeout(timeout time.Duration) *UpdateContactParams {
	var ()
	return &UpdateContactParams{

		timeout: timeout,
	}
}

// NewUpdateContactParamsWithContext creates a new UpdateContactParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateContactParamsWithContext(ctx context.Context) *UpdateContactParams {
	var ()
	return &UpdateContactParams{

		Context: ctx,
	}
}

// NewUpdateContactParamsWithHTTPClient creates a new UpdateContactParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateContactParamsWithHTTPClient(client *http.Client) *UpdateContactParams {
	var ()
	return &UpdateContactParams{
		HTTPClient: client,
	}
}

/*UpdateContactParams contains all the parameters to send to the API endpoint
for the update contact operation typically these are written to a http.Request
*/
type UpdateContactParams struct {

	/*Body*/
	Body *models.UpdateContactRequest
	/*ContactID*/
	ContactID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update contact params
func (o *UpdateContactParams) WithTimeout(timeout time.Duration) *UpdateContactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update contact params
func (o *UpdateContactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update contact params
func (o *UpdateContactParams) WithContext(ctx context.Context) *UpdateContactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update contact params
func (o *UpdateContactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update contact params
func (o *UpdateContactParams) WithHTTPClient(client *http.Client) *UpdateContactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update contact params
func (o *UpdateContactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update contact params
func (o *UpdateContactParams) WithBody(body *models.UpdateContactRequest) *UpdateContactParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update contact params
func (o *UpdateContactParams) SetBody(body *models.UpdateContactRequest) {
	o.Body = body
}

// WithContactID adds the contactID to the update contact params
func (o *UpdateContactParams) WithContactID(contactID string) *UpdateContactParams {
	o.SetContactID(contactID)
	return o
}

// SetContactID adds the contactId to the update contact params
func (o *UpdateContactParams) SetContactID(contactID string) {
	o.ContactID = contactID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateContactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param contactId
	if err := r.SetPathParam("contactId", o.ContactID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
