// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddDeviceToGroupReader is a Reader for the AddDeviceToGroup structure.
type AddDeviceToGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddDeviceToGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewAddDeviceToGroupDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewAddDeviceToGroupDefault creates a AddDeviceToGroupDefault with default headers values
func NewAddDeviceToGroupDefault(code int) *AddDeviceToGroupDefault {
	return &AddDeviceToGroupDefault{
		_statusCode: code,
	}
}

/*AddDeviceToGroupDefault handles this case with default header values.

successful operation
*/
type AddDeviceToGroupDefault struct {
	_statusCode int
}

// Code gets the status code for the add device to group default response
func (o *AddDeviceToGroupDefault) Code() int {
	return o._statusCode
}

func (o *AddDeviceToGroupDefault) Error() string {
	return fmt.Sprintf("[POST /groups/{groupId}/devices][%d] addDeviceToGroup default ", o._statusCode)
}

func (o *AddDeviceToGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
