// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetGroupFaxlineCallerIDReader is a Reader for the GetGroupFaxlineCallerID structure.
type GetGroupFaxlineCallerIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupFaxlineCallerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupFaxlineCallerIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupFaxlineCallerIDOK creates a GetGroupFaxlineCallerIDOK with default headers values
func NewGetGroupFaxlineCallerIDOK() *GetGroupFaxlineCallerIDOK {
	return &GetGroupFaxlineCallerIDOK{}
}

/*GetGroupFaxlineCallerIDOK handles this case with default header values.

successful operation
*/
type GetGroupFaxlineCallerIDOK struct {
	Payload *models.FaxlineCallerIDResponse
}

func (o *GetGroupFaxlineCallerIDOK) Error() string {
	return fmt.Sprintf("[GET /groupfaxlines/{faxlineId}/callerid][%d] getGroupFaxlineCallerIdOK  %+v", 200, o.Payload)
}

func (o *GetGroupFaxlineCallerIDOK) GetPayload() *models.FaxlineCallerIDResponse {
	return o.Payload
}

func (o *GetGroupFaxlineCallerIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FaxlineCallerIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
