// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupFaxlineNumbersParams creates a new GetGroupFaxlineNumbersParams object
// with the default values initialized.
func NewGetGroupFaxlineNumbersParams() *GetGroupFaxlineNumbersParams {
	var ()
	return &GetGroupFaxlineNumbersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupFaxlineNumbersParamsWithTimeout creates a new GetGroupFaxlineNumbersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGroupFaxlineNumbersParamsWithTimeout(timeout time.Duration) *GetGroupFaxlineNumbersParams {
	var ()
	return &GetGroupFaxlineNumbersParams{

		timeout: timeout,
	}
}

// NewGetGroupFaxlineNumbersParamsWithContext creates a new GetGroupFaxlineNumbersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGroupFaxlineNumbersParamsWithContext(ctx context.Context) *GetGroupFaxlineNumbersParams {
	var ()
	return &GetGroupFaxlineNumbersParams{

		Context: ctx,
	}
}

// NewGetGroupFaxlineNumbersParamsWithHTTPClient creates a new GetGroupFaxlineNumbersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGroupFaxlineNumbersParamsWithHTTPClient(client *http.Client) *GetGroupFaxlineNumbersParams {
	var ()
	return &GetGroupFaxlineNumbersParams{
		HTTPClient: client,
	}
}

/*GetGroupFaxlineNumbersParams contains all the parameters to send to the API endpoint
for the get group faxline numbers operation typically these are written to a http.Request
*/
type GetGroupFaxlineNumbersParams struct {

	/*FaxlineID
	  The unique fax line identifier

	*/
	FaxlineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) WithTimeout(timeout time.Duration) *GetGroupFaxlineNumbersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) WithContext(ctx context.Context) *GetGroupFaxlineNumbersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) WithHTTPClient(client *http.Client) *GetGroupFaxlineNumbersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFaxlineID adds the faxlineID to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) WithFaxlineID(faxlineID string) *GetGroupFaxlineNumbersParams {
	o.SetFaxlineID(faxlineID)
	return o
}

// SetFaxlineID adds the faxlineId to the get group faxline numbers params
func (o *GetGroupFaxlineNumbersParams) SetFaxlineID(faxlineID string) {
	o.FaxlineID = faxlineID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupFaxlineNumbersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param faxlineId
	if err := r.SetPathParam("faxlineId", o.FaxlineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
