// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetGroupUsersReader is a Reader for the GetGroupUsers structure.
type GetGroupUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupUsersOK creates a GetGroupUsersOK with default headers values
func NewGetGroupUsersOK() *GetGroupUsersOK {
	return &GetGroupUsersOK{}
}

/*GetGroupUsersOK handles this case with default header values.

successful operation
*/
type GetGroupUsersOK struct {
	Payload *models.GroupUsersResponse
}

func (o *GetGroupUsersOK) Error() string {
	return fmt.Sprintf("[GET /groups/{groupId}/users][%d] getGroupUsersOK  %+v", 200, o.Payload)
}

func (o *GetGroupUsersOK) GetPayload() *models.GroupUsersResponse {
	return o.Payload
}

func (o *GetGroupUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupUsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
