// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetGroupFaxlinesReader is a Reader for the GetGroupFaxlines structure.
type GetGroupFaxlinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupFaxlinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupFaxlinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupFaxlinesOK creates a GetGroupFaxlinesOK with default headers values
func NewGetGroupFaxlinesOK() *GetGroupFaxlinesOK {
	return &GetGroupFaxlinesOK{}
}

/*GetGroupFaxlinesOK handles this case with default header values.

successful operation
*/
type GetGroupFaxlinesOK struct {
	Payload *models.GroupFaxlinesResponse
}

func (o *GetGroupFaxlinesOK) Error() string {
	return fmt.Sprintf("[GET /groups/{groupId}/faxlines][%d] getGroupFaxlinesOK  %+v", 200, o.Payload)
}

func (o *GetGroupFaxlinesOK) GetPayload() *models.GroupFaxlinesResponse {
	return o.Payload
}

func (o *GetGroupFaxlinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupFaxlinesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
