// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetGroupFaxlineNumbersReader is a Reader for the GetGroupFaxlineNumbers structure.
type GetGroupFaxlineNumbersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupFaxlineNumbersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupFaxlineNumbersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupFaxlineNumbersOK creates a GetGroupFaxlineNumbersOK with default headers values
func NewGetGroupFaxlineNumbersOK() *GetGroupFaxlineNumbersOK {
	return &GetGroupFaxlineNumbersOK{}
}

/*GetGroupFaxlineNumbersOK handles this case with default header values.

successful operation
*/
type GetGroupFaxlineNumbersOK struct {
	Payload *models.EndpointNumbersResponse
}

func (o *GetGroupFaxlineNumbersOK) Error() string {
	return fmt.Sprintf("[GET /groupfaxlines/{faxlineId}/numbers][%d] getGroupFaxlineNumbersOK  %+v", 200, o.Payload)
}

func (o *GetGroupFaxlineNumbersOK) GetPayload() *models.EndpointNumbersResponse {
	return o.Payload
}

func (o *GetGroupFaxlineNumbersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EndpointNumbersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
