// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupFaxlinesForUserParams creates a new GetGroupFaxlinesForUserParams object
// with the default values initialized.
func NewGetGroupFaxlinesForUserParams() *GetGroupFaxlinesForUserParams {
	var ()
	return &GetGroupFaxlinesForUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupFaxlinesForUserParamsWithTimeout creates a new GetGroupFaxlinesForUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGroupFaxlinesForUserParamsWithTimeout(timeout time.Duration) *GetGroupFaxlinesForUserParams {
	var ()
	return &GetGroupFaxlinesForUserParams{

		timeout: timeout,
	}
}

// NewGetGroupFaxlinesForUserParamsWithContext creates a new GetGroupFaxlinesForUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGroupFaxlinesForUserParamsWithContext(ctx context.Context) *GetGroupFaxlinesForUserParams {
	var ()
	return &GetGroupFaxlinesForUserParams{

		Context: ctx,
	}
}

// NewGetGroupFaxlinesForUserParamsWithHTTPClient creates a new GetGroupFaxlinesForUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGroupFaxlinesForUserParamsWithHTTPClient(client *http.Client) *GetGroupFaxlinesForUserParams {
	var ()
	return &GetGroupFaxlinesForUserParams{
		HTTPClient: client,
	}
}

/*GetGroupFaxlinesForUserParams contains all the parameters to send to the API endpoint
for the get group faxlines for user operation typically these are written to a http.Request
*/
type GetGroupFaxlinesForUserParams struct {

	/*UserID
	  The unique user identifier

	*/
	UserID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) WithTimeout(timeout time.Duration) *GetGroupFaxlinesForUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) WithContext(ctx context.Context) *GetGroupFaxlinesForUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) WithHTTPClient(client *http.Client) *GetGroupFaxlinesForUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) WithUserID(userID *string) *GetGroupFaxlinesForUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get group faxlines for user params
func (o *GetGroupFaxlinesForUserParams) SetUserID(userID *string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupFaxlinesForUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserID != nil {

		// query param userId
		var qrUserID string
		if o.UserID != nil {
			qrUserID = *o.UserID
		}
		qUserID := qrUserID
		if qUserID != "" {
			if err := r.SetQueryParam("userId", qUserID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
