// Code generated by go-swagger; DO NOT EDIT.

package blacklist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewAddIncomingEntryParams creates a new AddIncomingEntryParams object
// with the default values initialized.
func NewAddIncomingEntryParams() *AddIncomingEntryParams {
	var ()
	return &AddIncomingEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddIncomingEntryParamsWithTimeout creates a new AddIncomingEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddIncomingEntryParamsWithTimeout(timeout time.Duration) *AddIncomingEntryParams {
	var ()
	return &AddIncomingEntryParams{

		timeout: timeout,
	}
}

// NewAddIncomingEntryParamsWithContext creates a new AddIncomingEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddIncomingEntryParamsWithContext(ctx context.Context) *AddIncomingEntryParams {
	var ()
	return &AddIncomingEntryParams{

		Context: ctx,
	}
}

// NewAddIncomingEntryParamsWithHTTPClient creates a new AddIncomingEntryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddIncomingEntryParamsWithHTTPClient(client *http.Client) *AddIncomingEntryParams {
	var ()
	return &AddIncomingEntryParams{
		HTTPClient: client,
	}
}

/*AddIncomingEntryParams contains all the parameters to send to the API endpoint
for the add incoming entry operation typically these are written to a http.Request
*/
type AddIncomingEntryParams struct {

	/*Body*/
	Body *models.IncomingEntry

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add incoming entry params
func (o *AddIncomingEntryParams) WithTimeout(timeout time.Duration) *AddIncomingEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add incoming entry params
func (o *AddIncomingEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add incoming entry params
func (o *AddIncomingEntryParams) WithContext(ctx context.Context) *AddIncomingEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add incoming entry params
func (o *AddIncomingEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add incoming entry params
func (o *AddIncomingEntryParams) WithHTTPClient(client *http.Client) *AddIncomingEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add incoming entry params
func (o *AddIncomingEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add incoming entry params
func (o *AddIncomingEntryParams) WithBody(body *models.IncomingEntry) *AddIncomingEntryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add incoming entry params
func (o *AddIncomingEntryParams) SetBody(body *models.IncomingEntry) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddIncomingEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
