// Code generated by go-swagger; DO NOT EDIT.

package sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddCallerIDReader is a Reader for the AddCallerID structure.
type AddCallerIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddCallerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 402:
		result := NewAddCallerIDPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddCallerIDPaymentRequired creates a AddCallerIDPaymentRequired with default headers values
func NewAddCallerIDPaymentRequired() *AddCallerIDPaymentRequired {
	return &AddCallerIDPaymentRequired{}
}

/*AddCallerIDPaymentRequired handles this case with default header values.

Insufficient funds
*/
type AddCallerIDPaymentRequired struct {
}

func (o *AddCallerIDPaymentRequired) Error() string {
	return fmt.Sprintf("[POST /{userId}/sms/{smsId}/callerids][%d] addCallerIdPaymentRequired ", 402)
}

func (o *AddCallerIDPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
