// Code generated by go-swagger; DO NOT EDIT.

package sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetSmsCallerIdsReader is a Reader for the GetSmsCallerIds structure.
type GetSmsCallerIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSmsCallerIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSmsCallerIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSmsCallerIdsOK creates a GetSmsCallerIdsOK with default headers values
func NewGetSmsCallerIdsOK() *GetSmsCallerIdsOK {
	return &GetSmsCallerIdsOK{}
}

/*GetSmsCallerIdsOK handles this case with default header values.

successful operation
*/
type GetSmsCallerIdsOK struct {
	Payload *models.SmsCallerIdsResponse
}

func (o *GetSmsCallerIdsOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/sms/{smsId}/callerids][%d] getSmsCallerIdsOK  %+v", 200, o.Payload)
}

func (o *GetSmsCallerIdsOK) GetPayload() *models.SmsCallerIdsResponse {
	return o.Payload
}

func (o *GetSmsCallerIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SmsCallerIdsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
