// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewSetDefaultDeviceParams creates a new SetDefaultDeviceParams object
// with the default values initialized.
func NewSetDefaultDeviceParams() *SetDefaultDeviceParams {
	var ()
	return &SetDefaultDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetDefaultDeviceParamsWithTimeout creates a new SetDefaultDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetDefaultDeviceParamsWithTimeout(timeout time.Duration) *SetDefaultDeviceParams {
	var ()
	return &SetDefaultDeviceParams{

		timeout: timeout,
	}
}

// NewSetDefaultDeviceParamsWithContext creates a new SetDefaultDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetDefaultDeviceParamsWithContext(ctx context.Context) *SetDefaultDeviceParams {
	var ()
	return &SetDefaultDeviceParams{

		Context: ctx,
	}
}

// NewSetDefaultDeviceParamsWithHTTPClient creates a new SetDefaultDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetDefaultDeviceParamsWithHTTPClient(client *http.Client) *SetDefaultDeviceParams {
	var ()
	return &SetDefaultDeviceParams{
		HTTPClient: client,
	}
}

/*SetDefaultDeviceParams contains all the parameters to send to the API endpoint
for the set default device operation typically these are written to a http.Request
*/
type SetDefaultDeviceParams struct {

	/*Body*/
	Body *models.SetDefaultDeviceRequest
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set default device params
func (o *SetDefaultDeviceParams) WithTimeout(timeout time.Duration) *SetDefaultDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set default device params
func (o *SetDefaultDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set default device params
func (o *SetDefaultDeviceParams) WithContext(ctx context.Context) *SetDefaultDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set default device params
func (o *SetDefaultDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set default device params
func (o *SetDefaultDeviceParams) WithHTTPClient(client *http.Client) *SetDefaultDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set default device params
func (o *SetDefaultDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set default device params
func (o *SetDefaultDeviceParams) WithBody(body *models.SetDefaultDeviceRequest) *SetDefaultDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set default device params
func (o *SetDefaultDeviceParams) SetBody(body *models.SetDefaultDeviceRequest) {
	o.Body = body
}

// WithUserID adds the userID to the set default device params
func (o *SetDefaultDeviceParams) WithUserID(userID string) *SetDefaultDeviceParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the set default device params
func (o *SetDefaultDeviceParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *SetDefaultDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
