// Code generated by go-swagger; DO NOT EDIT.

package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetAddressesReader is a Reader for the GetAddresses structure.
type GetAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAddressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAddressesOK creates a GetAddressesOK with default headers values
func NewGetAddressesOK() *GetAddressesOK {
	return &GetAddressesOK{}
}

/*GetAddressesOK handles this case with default header values.

successful operation
*/
type GetAddressesOK struct {
	Payload *models.AddressesResponse
}

func (o *GetAddressesOK) Error() string {
	return fmt.Sprintf("[GET /addresses][%d] getAddressesOK  %+v", 200, o.Payload)
}

func (o *GetAddressesOK) GetPayload() *models.AddressesResponse {
	return o.Payload
}

func (o *GetAddressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddressesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
