// Code generated by go-swagger; DO NOT EDIT.

package portings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetPortingReader is a Reader for the GetPorting structure.
type GetPortingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPortingOK creates a GetPortingOK with default headers values
func NewGetPortingOK() *GetPortingOK {
	return &GetPortingOK{}
}

/*GetPortingOK handles this case with default header values.

successful operation
*/
type GetPortingOK struct {
	Payload *models.PortingResponse
}

func (o *GetPortingOK) Error() string {
	return fmt.Sprintf("[GET /portings/{portingId}][%d] getPortingOK  %+v", 200, o.Payload)
}

func (o *GetPortingOK) GetPayload() *models.PortingResponse {
	return o.Payload
}

func (o *GetPortingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
