// Code generated by go-swagger; DO NOT EDIT.

package portings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetPortingsReader is a Reader for the GetPortings structure.
type GetPortingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPortingsOK creates a GetPortingsOK with default headers values
func NewGetPortingsOK() *GetPortingsOK {
	return &GetPortingsOK{}
}

/*GetPortingsOK handles this case with default header values.

successful operation
*/
type GetPortingsOK struct {
	Payload *models.PortingsResponse
}

func (o *GetPortingsOK) Error() string {
	return fmt.Sprintf("[GET /portings][%d] getPortingsOK  %+v", 200, o.Payload)
}

func (o *GetPortingsOK) GetPayload() *models.PortingsResponse {
	return o.Payload
}

func (o *GetPortingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
