// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewSetSipgateIoUrlsParams creates a new SetSipgateIoUrlsParams object
// with the default values initialized.
func NewSetSipgateIoUrlsParams() *SetSipgateIoUrlsParams {
	var ()
	return &SetSipgateIoUrlsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetSipgateIoUrlsParamsWithTimeout creates a new SetSipgateIoUrlsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetSipgateIoUrlsParamsWithTimeout(timeout time.Duration) *SetSipgateIoUrlsParams {
	var ()
	return &SetSipgateIoUrlsParams{

		timeout: timeout,
	}
}

// NewSetSipgateIoUrlsParamsWithContext creates a new SetSipgateIoUrlsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetSipgateIoUrlsParamsWithContext(ctx context.Context) *SetSipgateIoUrlsParams {
	var ()
	return &SetSipgateIoUrlsParams{

		Context: ctx,
	}
}

// NewSetSipgateIoUrlsParamsWithHTTPClient creates a new SetSipgateIoUrlsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetSipgateIoUrlsParamsWithHTTPClient(client *http.Client) *SetSipgateIoUrlsParams {
	var ()
	return &SetSipgateIoUrlsParams{
		HTTPClient: client,
	}
}

/*SetSipgateIoUrlsParams contains all the parameters to send to the API endpoint
for the set sipgate io urls operation typically these are written to a http.Request
*/
type SetSipgateIoUrlsParams struct {

	/*Body*/
	Body *models.SetSipgateIoAccountSettingsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) WithTimeout(timeout time.Duration) *SetSipgateIoUrlsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) WithContext(ctx context.Context) *SetSipgateIoUrlsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) WithHTTPClient(client *http.Client) *SetSipgateIoUrlsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) WithBody(body *models.SetSipgateIoAccountSettingsRequest) *SetSipgateIoUrlsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set sipgate io urls params
func (o *SetSipgateIoUrlsParams) SetBody(body *models.SetSipgateIoAccountSettingsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SetSipgateIoUrlsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
