// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetCallsReader is a Reader for the GetCalls structure.
type GetCallsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCallsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCallsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCallsOK creates a GetCallsOK with default headers values
func NewGetCallsOK() *GetCallsOK {
	return &GetCallsOK{}
}

/*GetCallsOK handles this case with default header values.

Success
*/
type GetCallsOK struct {
	Payload *models.Calls
}

func (o *GetCallsOK) Error() string {
	return fmt.Sprintf("[GET /calls][%d] getCallsOK  %+v", 200, o.Payload)
}

func (o *GetCallsOK) GetPayload() *models.Calls {
	return o.Payload
}

func (o *GetCallsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Calls)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
