// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCallsParams creates a new GetCallsParams object
// with the default values initialized.
func NewGetCallsParams() *GetCallsParams {

	return &GetCallsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCallsParamsWithTimeout creates a new GetCallsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCallsParamsWithTimeout(timeout time.Duration) *GetCallsParams {

	return &GetCallsParams{

		timeout: timeout,
	}
}

// NewGetCallsParamsWithContext creates a new GetCallsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCallsParamsWithContext(ctx context.Context) *GetCallsParams {

	return &GetCallsParams{

		Context: ctx,
	}
}

// NewGetCallsParamsWithHTTPClient creates a new GetCallsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCallsParamsWithHTTPClient(client *http.Client) *GetCallsParams {

	return &GetCallsParams{
		HTTPClient: client,
	}
}

/*GetCallsParams contains all the parameters to send to the API endpoint
for the get calls operation typically these are written to a http.Request
*/
type GetCallsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get calls params
func (o *GetCallsParams) WithTimeout(timeout time.Duration) *GetCallsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get calls params
func (o *GetCallsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get calls params
func (o *GetCallsParams) WithContext(ctx context.Context) *GetCallsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get calls params
func (o *GetCallsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get calls params
func (o *GetCallsParams) WithHTTPClient(client *http.Client) *GetCallsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get calls params
func (o *GetCallsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCallsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
