// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHangupCallParams creates a new HangupCallParams object
// with the default values initialized.
func NewHangupCallParams() *HangupCallParams {
	var ()
	return &HangupCallParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHangupCallParamsWithTimeout creates a new HangupCallParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHangupCallParamsWithTimeout(timeout time.Duration) *HangupCallParams {
	var ()
	return &HangupCallParams{

		timeout: timeout,
	}
}

// NewHangupCallParamsWithContext creates a new HangupCallParams object
// with the default values initialized, and the ability to set a context for a request
func NewHangupCallParamsWithContext(ctx context.Context) *HangupCallParams {
	var ()
	return &HangupCallParams{

		Context: ctx,
	}
}

// NewHangupCallParamsWithHTTPClient creates a new HangupCallParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHangupCallParamsWithHTTPClient(client *http.Client) *HangupCallParams {
	var ()
	return &HangupCallParams{
		HTTPClient: client,
	}
}

/*HangupCallParams contains all the parameters to send to the API endpoint
for the hangup call operation typically these are written to a http.Request
*/
type HangupCallParams struct {

	/*CallID*/
	CallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the hangup call params
func (o *HangupCallParams) WithTimeout(timeout time.Duration) *HangupCallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hangup call params
func (o *HangupCallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hangup call params
func (o *HangupCallParams) WithContext(ctx context.Context) *HangupCallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hangup call params
func (o *HangupCallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hangup call params
func (o *HangupCallParams) WithHTTPClient(client *http.Client) *HangupCallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hangup call params
func (o *HangupCallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCallID adds the callID to the hangup call params
func (o *HangupCallParams) WithCallID(callID string) *HangupCallParams {
	o.SetCallID(callID)
	return o
}

// SetCallID adds the callId to the hangup call params
func (o *HangupCallParams) SetCallID(callID string) {
	o.CallID = callID
}

// WriteToRequest writes these params to a swagger request
func (o *HangupCallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param callId
	if err := r.SetPathParam("callId", o.CallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
