// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewSetCallMutedParams creates a new SetCallMutedParams object
// with the default values initialized.
func NewSetCallMutedParams() *SetCallMutedParams {
	var ()
	return &SetCallMutedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCallMutedParamsWithTimeout creates a new SetCallMutedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCallMutedParamsWithTimeout(timeout time.Duration) *SetCallMutedParams {
	var ()
	return &SetCallMutedParams{

		timeout: timeout,
	}
}

// NewSetCallMutedParamsWithContext creates a new SetCallMutedParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCallMutedParamsWithContext(ctx context.Context) *SetCallMutedParams {
	var ()
	return &SetCallMutedParams{

		Context: ctx,
	}
}

// NewSetCallMutedParamsWithHTTPClient creates a new SetCallMutedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCallMutedParamsWithHTTPClient(client *http.Client) *SetCallMutedParams {
	var ()
	return &SetCallMutedParams{
		HTTPClient: client,
	}
}

/*SetCallMutedParams contains all the parameters to send to the API endpoint
for the set call muted operation typically these are written to a http.Request
*/
type SetCallMutedParams struct {

	/*Body*/
	Body *models.BooleanRequest
	/*CallID*/
	CallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set call muted params
func (o *SetCallMutedParams) WithTimeout(timeout time.Duration) *SetCallMutedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set call muted params
func (o *SetCallMutedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set call muted params
func (o *SetCallMutedParams) WithContext(ctx context.Context) *SetCallMutedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set call muted params
func (o *SetCallMutedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set call muted params
func (o *SetCallMutedParams) WithHTTPClient(client *http.Client) *SetCallMutedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set call muted params
func (o *SetCallMutedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set call muted params
func (o *SetCallMutedParams) WithBody(body *models.BooleanRequest) *SetCallMutedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set call muted params
func (o *SetCallMutedParams) SetBody(body *models.BooleanRequest) {
	o.Body = body
}

// WithCallID adds the callID to the set call muted params
func (o *SetCallMutedParams) WithCallID(callID string) *SetCallMutedParams {
	o.SetCallID(callID)
	return o
}

// SetCallID adds the callId to the set call muted params
func (o *SetCallMutedParams) SetCallID(callID string) {
	o.CallID = callID
}

// WriteToRequest writes these params to a swagger request
func (o *SetCallMutedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param callId
	if err := r.SetPathParam("callId", o.CallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
