// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewSetCallRecordingParams creates a new SetCallRecordingParams object
// with the default values initialized.
func NewSetCallRecordingParams() *SetCallRecordingParams {
	var ()
	return &SetCallRecordingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCallRecordingParamsWithTimeout creates a new SetCallRecordingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCallRecordingParamsWithTimeout(timeout time.Duration) *SetCallRecordingParams {
	var ()
	return &SetCallRecordingParams{

		timeout: timeout,
	}
}

// NewSetCallRecordingParamsWithContext creates a new SetCallRecordingParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCallRecordingParamsWithContext(ctx context.Context) *SetCallRecordingParams {
	var ()
	return &SetCallRecordingParams{

		Context: ctx,
	}
}

// NewSetCallRecordingParamsWithHTTPClient creates a new SetCallRecordingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCallRecordingParamsWithHTTPClient(client *http.Client) *SetCallRecordingParams {
	var ()
	return &SetCallRecordingParams{
		HTTPClient: client,
	}
}

/*SetCallRecordingParams contains all the parameters to send to the API endpoint
for the set call recording operation typically these are written to a http.Request
*/
type SetCallRecordingParams struct {

	/*Body*/
	Body *models.RecordingRequest
	/*CallID*/
	CallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set call recording params
func (o *SetCallRecordingParams) WithTimeout(timeout time.Duration) *SetCallRecordingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set call recording params
func (o *SetCallRecordingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set call recording params
func (o *SetCallRecordingParams) WithContext(ctx context.Context) *SetCallRecordingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set call recording params
func (o *SetCallRecordingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set call recording params
func (o *SetCallRecordingParams) WithHTTPClient(client *http.Client) *SetCallRecordingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set call recording params
func (o *SetCallRecordingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set call recording params
func (o *SetCallRecordingParams) WithBody(body *models.RecordingRequest) *SetCallRecordingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set call recording params
func (o *SetCallRecordingParams) SetBody(body *models.RecordingRequest) {
	o.Body = body
}

// WithCallID adds the callID to the set call recording params
func (o *SetCallRecordingParams) WithCallID(callID string) *SetCallRecordingParams {
	o.SetCallID(callID)
	return o
}

// SetCallID adds the callId to the set call recording params
func (o *SetCallRecordingParams) SetCallID(callID string) {
	o.CallID = callID
}

// WriteToRequest writes these params to a swagger request
func (o *SetCallRecordingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param callId
	if err := r.SetPathParam("callId", o.CallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
