// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewTransferCallParams creates a new TransferCallParams object
// with the default values initialized.
func NewTransferCallParams() *TransferCallParams {
	var ()
	return &TransferCallParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTransferCallParamsWithTimeout creates a new TransferCallParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTransferCallParamsWithTimeout(timeout time.Duration) *TransferCallParams {
	var ()
	return &TransferCallParams{

		timeout: timeout,
	}
}

// NewTransferCallParamsWithContext creates a new TransferCallParams object
// with the default values initialized, and the ability to set a context for a request
func NewTransferCallParamsWithContext(ctx context.Context) *TransferCallParams {
	var ()
	return &TransferCallParams{

		Context: ctx,
	}
}

// NewTransferCallParamsWithHTTPClient creates a new TransferCallParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTransferCallParamsWithHTTPClient(client *http.Client) *TransferCallParams {
	var ()
	return &TransferCallParams{
		HTTPClient: client,
	}
}

/*TransferCallParams contains all the parameters to send to the API endpoint
for the transfer call operation typically these are written to a http.Request
*/
type TransferCallParams struct {

	/*Body*/
	Body *models.TransferRequest
	/*CallID*/
	CallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the transfer call params
func (o *TransferCallParams) WithTimeout(timeout time.Duration) *TransferCallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer call params
func (o *TransferCallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer call params
func (o *TransferCallParams) WithContext(ctx context.Context) *TransferCallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer call params
func (o *TransferCallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer call params
func (o *TransferCallParams) WithHTTPClient(client *http.Client) *TransferCallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer call params
func (o *TransferCallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the transfer call params
func (o *TransferCallParams) WithBody(body *models.TransferRequest) *TransferCallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the transfer call params
func (o *TransferCallParams) SetBody(body *models.TransferRequest) {
	o.Body = body
}

// WithCallID adds the callID to the transfer call params
func (o *TransferCallParams) WithCallID(callID string) *TransferCallParams {
	o.SetCallID(callID)
	return o
}

// SetCallID adds the callId to the transfer call params
func (o *TransferCallParams) SetCallID(callID string) {
	o.CallID = callID
}

// WriteToRequest writes these params to a swagger request
func (o *TransferCallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param callId
	if err := r.SetPathParam("callId", o.CallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
