// Code generated by go-swagger; DO NOT EDIT.

package rtcm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TransferCallReader is a Reader for the TransferCall structure.
type TransferCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewTransferCallNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewTransferCallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTransferCallNoContent creates a TransferCallNoContent with default headers values
func NewTransferCallNoContent() *TransferCallNoContent {
	return &TransferCallNoContent{}
}

/*TransferCallNoContent handles this case with default header values.

Success
*/
type TransferCallNoContent struct {
}

func (o *TransferCallNoContent) Error() string {
	return fmt.Sprintf("[POST /calls/{callId}/transfer][%d] transferCallNoContent ", 204)
}

func (o *TransferCallNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransferCallNotFound creates a TransferCallNotFound with default headers values
func NewTransferCallNotFound() *TransferCallNotFound {
	return &TransferCallNotFound{}
}

/*TransferCallNotFound handles this case with default header values.

Call not found
*/
type TransferCallNotFound struct {
}

func (o *TransferCallNotFound) Error() string {
	return fmt.Sprintf("[POST /calls/{callId}/transfer][%d] transferCallNotFound ", 404)
}

func (o *TransferCallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
