// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddFaxSmsNotificationRequest add fax sms notification request
//
// swagger:model AddFaxSmsNotificationRequest
type AddFaxSmsNotificationRequest struct {

	// direction
	// Required: true
	// Enum: [INCOMING OUTGOING]
	Direction *string `json:"direction"`

	// faxline Id
	// Required: true
	FaxlineID *string `json:"faxlineId"`

	// number
	// Required: true
	Number *string `json:"number"`
}

// Validate validates this add fax sms notification request
func (m *AddFaxSmsNotificationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFaxlineID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var addFaxSmsNotificationRequestTypeDirectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["INCOMING","OUTGOING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		addFaxSmsNotificationRequestTypeDirectionPropEnum = append(addFaxSmsNotificationRequestTypeDirectionPropEnum, v)
	}
}

const (

	// AddFaxSmsNotificationRequestDirectionINCOMING captures enum value "INCOMING"
	AddFaxSmsNotificationRequestDirectionINCOMING string = "INCOMING"

	// AddFaxSmsNotificationRequestDirectionOUTGOING captures enum value "OUTGOING"
	AddFaxSmsNotificationRequestDirectionOUTGOING string = "OUTGOING"
)

// prop value enum
func (m *AddFaxSmsNotificationRequest) validateDirectionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, addFaxSmsNotificationRequestTypeDirectionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *AddFaxSmsNotificationRequest) validateDirection(formats strfmt.Registry) error {

	if err := validate.Required("direction", "body", m.Direction); err != nil {
		return err
	}

	// value enum
	if err := m.validateDirectionEnum("direction", "body", *m.Direction); err != nil {
		return err
	}

	return nil
}

func (m *AddFaxSmsNotificationRequest) validateFaxlineID(formats strfmt.Registry) error {

	if err := validate.Required("faxlineId", "body", m.FaxlineID); err != nil {
		return err
	}

	return nil
}

func (m *AddFaxSmsNotificationRequest) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddFaxSmsNotificationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddFaxSmsNotificationRequest) UnmarshalBinary(b []byte) error {
	var res AddFaxSmsNotificationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
