// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangeNumberSettingsRequest change number settings request
//
// swagger:model ChangeNumberSettingsRequest
type ChangeNumberSettingsRequest struct {

	// endpoint Id
	EndpointID string `json:"endpointId,omitempty"`

	// quick dial
	QuickDial *bool `json:"quickDial,omitempty"`

	// release for mnp
	ReleaseForMnp *bool `json:"releaseForMnp,omitempty"`
}

// Validate validates this change number settings request
func (m *ChangeNumberSettingsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangeNumberSettingsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangeNumberSettingsRequest) UnmarshalBinary(b []byte) error {
	var res ChangeNumberSettingsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
