// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangeVoicemailTranscriptionRequest change voicemail transcription request
//
// swagger:model ChangeVoicemailTranscriptionRequest
type ChangeVoicemailTranscriptionRequest struct {

	// active
	Active *bool `json:"active,omitempty"`
}

// Validate validates this change voicemail transcription request
func (m *ChangeVoicemailTranscriptionRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangeVoicemailTranscriptionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangeVoicemailTranscriptionRequest) UnmarshalBinary(b []byte) error {
	var res ChangeVoicemailTranscriptionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
