// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContactResponse contact response
//
// swagger:model ContactResponse
type ContactResponse struct {

	// addresses
	Addresses []*AddressResponse `json:"addresses"`

	// emails
	Emails []*EMailResponse `json:"emails"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// numbers
	Numbers []*NumberResponse `json:"numbers"`

	// organization
	Organization [][]string `json:"organization"`

	// picture
	Picture string `json:"picture,omitempty"`

	// scope
	// Enum: [PRIVATE SHARED INTERNAL]
	Scope string `json:"scope,omitempty"`
}

// Validate validates this contact response
func (m *ContactResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddresses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumbers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContactResponse) validateAddresses(formats strfmt.Registry) error {

	if swag.IsZero(m.Addresses) { // not required
		return nil
	}

	for i := 0; i < len(m.Addresses); i++ {
		if swag.IsZero(m.Addresses[i]) { // not required
			continue
		}

		if m.Addresses[i] != nil {
			if err := m.Addresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("addresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ContactResponse) validateEmails(formats strfmt.Registry) error {

	if swag.IsZero(m.Emails) { // not required
		return nil
	}

	for i := 0; i < len(m.Emails); i++ {
		if swag.IsZero(m.Emails[i]) { // not required
			continue
		}

		if m.Emails[i] != nil {
			if err := m.Emails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("emails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ContactResponse) validateNumbers(formats strfmt.Registry) error {

	if swag.IsZero(m.Numbers) { // not required
		return nil
	}

	for i := 0; i < len(m.Numbers); i++ {
		if swag.IsZero(m.Numbers[i]) { // not required
			continue
		}

		if m.Numbers[i] != nil {
			if err := m.Numbers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("numbers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var contactResponseTypeScopePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PRIVATE","SHARED","INTERNAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		contactResponseTypeScopePropEnum = append(contactResponseTypeScopePropEnum, v)
	}
}

const (

	// ContactResponseScopePRIVATE captures enum value "PRIVATE"
	ContactResponseScopePRIVATE string = "PRIVATE"

	// ContactResponseScopeSHARED captures enum value "SHARED"
	ContactResponseScopeSHARED string = "SHARED"

	// ContactResponseScopeINTERNAL captures enum value "INTERNAL"
	ContactResponseScopeINTERNAL string = "INTERNAL"
)

// prop value enum
func (m *ContactResponse) validateScopeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, contactResponseTypeScopePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ContactResponse) validateScope(formats strfmt.Registry) error {

	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	// value enum
	if err := m.validateScopeEnum("scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContactResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContactResponse) UnmarshalBinary(b []byte) error {
	var res ContactResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
