// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FaxlineResponse faxline response
//
// swagger:model FaxlineResponse
type FaxlineResponse struct {

	// alias
	Alias string `json:"alias,omitempty"`

	// can receive
	CanReceive *bool `json:"canReceive,omitempty"`

	// can send
	CanSend *bool `json:"canSend,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// tagline
	Tagline string `json:"tagline,omitempty"`
}

// Validate validates this faxline response
func (m *FaxlineResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FaxlineResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FaxlineResponse) UnmarshalBinary(b []byte) error {
	var res FaxlineResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
