// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Forwarding forwarding
//
// swagger:model Forwarding
type Forwarding struct {

	// active
	Active *bool `json:"active,omitempty"`

	// destination
	Destination string `json:"destination,omitempty"`

	// timeout
	// Maximum: 600
	Timeout int32 `json:"timeout,omitempty"`
}

// Validate validates this forwarding
func (m *Forwarding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimeout(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Forwarding) validateTimeout(formats strfmt.Registry) error {

	if swag.IsZero(m.Timeout) { // not required
		return nil
	}

	if err := validate.MaximumInt("timeout", "body", int64(m.Timeout), 600, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Forwarding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Forwarding) UnmarshalBinary(b []byte) error {
	var res Forwarding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
