// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParallelForwardingResponse parallel forwarding response
//
// swagger:model ParallelForwardingResponse
type ParallelForwardingResponse struct {

	// active
	Active *bool `json:"active,omitempty"`

	// alias
	Alias string `json:"alias,omitempty"`

	// destination
	Destination string `json:"destination,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this parallel forwarding response
func (m *ParallelForwardingResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParallelForwardingResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParallelForwardingResponse) UnmarshalBinary(b []byte) error {
	var res ParallelForwardingResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
