// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PhonelineSipgateIoResponse phoneline sipgate io response
//
// swagger:model PhonelineSipgateIoResponse
type PhonelineSipgateIoResponse struct {

	// allow self signed
	AllowSelfSigned *bool `json:"allowSelfSigned,omitempty"`

	// certificate
	Certificate string `json:"certificate,omitempty"`

	// incoming active
	IncomingActive *bool `json:"incomingActive,omitempty"`

	// incoming Url
	IncomingURL string `json:"incomingUrl,omitempty"`

	// log
	Log *bool `json:"log,omitempty"`

	// outgoing active
	OutgoingActive *bool `json:"outgoingActive,omitempty"`

	// outgoing Url
	OutgoingURL string `json:"outgoingUrl,omitempty"`
}

// Validate validates this phoneline sipgate io response
func (m *PhonelineSipgateIoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhonelineSipgateIoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhonelineSipgateIoResponse) UnmarshalBinary(b []byte) error {
	var res PhonelineSipgateIoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
