// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PortingResponse porting response
//
// swagger:model PortingResponse
type PortingResponse struct {

	// id
	ID string `json:"id,omitempty"`

	// numbers
	Numbers []*PortingNumberResponse `json:"numbers"`

	// pending
	Pending *bool `json:"pending,omitempty"`

	// port date
	PortDate string `json:"portDate,omitempty"`

	// revocable
	Revocable *bool `json:"revocable,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`
}

// Validate validates this porting response
func (m *PortingResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNumbers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortingResponse) validateNumbers(formats strfmt.Registry) error {

	if swag.IsZero(m.Numbers) { // not required
		return nil
	}

	for i := 0; i < len(m.Numbers); i++ {
		if swag.IsZero(m.Numbers[i]) { // not required
			continue
		}

		if m.Numbers[i] != nil {
			if err := m.Numbers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("numbers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PortingResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortingResponse) UnmarshalBinary(b []byte) error {
	var res PortingResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
