// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegisterDeviceResponse register device response
//
// swagger:model RegisterDeviceResponse
type RegisterDeviceResponse struct {

	// active groups
	ActiveGroups []*ActiveRouting `json:"activeGroups"`

	// active phonelines
	ActivePhonelines []*ActiveRouting `json:"activePhonelines"`

	// address Url
	AddressURL string `json:"addressUrl,omitempty"`

	// alias
	Alias string `json:"alias,omitempty"`

	// credentials
	Credentials *CredentialsResponse `json:"credentials,omitempty"`

	// dnd
	Dnd *bool `json:"dnd,omitempty"`

	// emergency address Id
	EmergencyAddressID string `json:"emergencyAddressId,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// online
	Online *bool `json:"online,omitempty"`

	// registered
	Registered []*RegisteredDevice `json:"registered"`

	// type
	// Enum: [REGISTER MOBILE EXTERNAL]
	Type string `json:"type,omitempty"`
}

// Validate validates this register device response
func (m *RegisterDeviceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActiveGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateActivePhonelines(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentials(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegistered(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterDeviceResponse) validateActiveGroups(formats strfmt.Registry) error {

	if swag.IsZero(m.ActiveGroups) { // not required
		return nil
	}

	for i := 0; i < len(m.ActiveGroups); i++ {
		if swag.IsZero(m.ActiveGroups[i]) { // not required
			continue
		}

		if m.ActiveGroups[i] != nil {
			if err := m.ActiveGroups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("activeGroups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RegisterDeviceResponse) validateActivePhonelines(formats strfmt.Registry) error {

	if swag.IsZero(m.ActivePhonelines) { // not required
		return nil
	}

	for i := 0; i < len(m.ActivePhonelines); i++ {
		if swag.IsZero(m.ActivePhonelines[i]) { // not required
			continue
		}

		if m.ActivePhonelines[i] != nil {
			if err := m.ActivePhonelines[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("activePhonelines" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RegisterDeviceResponse) validateCredentials(formats strfmt.Registry) error {

	if swag.IsZero(m.Credentials) { // not required
		return nil
	}

	if m.Credentials != nil {
		if err := m.Credentials.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("credentials")
			}
			return err
		}
	}

	return nil
}

func (m *RegisterDeviceResponse) validateRegistered(formats strfmt.Registry) error {

	if swag.IsZero(m.Registered) { // not required
		return nil
	}

	for i := 0; i < len(m.Registered); i++ {
		if swag.IsZero(m.Registered[i]) { // not required
			continue
		}

		if m.Registered[i] != nil {
			if err := m.Registered[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("registered" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var registerDeviceResponseTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["REGISTER","MOBILE","EXTERNAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		registerDeviceResponseTypeTypePropEnum = append(registerDeviceResponseTypeTypePropEnum, v)
	}
}

const (

	// RegisterDeviceResponseTypeREGISTER captures enum value "REGISTER"
	RegisterDeviceResponseTypeREGISTER string = "REGISTER"

	// RegisterDeviceResponseTypeMOBILE captures enum value "MOBILE"
	RegisterDeviceResponseTypeMOBILE string = "MOBILE"

	// RegisterDeviceResponseTypeEXTERNAL captures enum value "EXTERNAL"
	RegisterDeviceResponseTypeEXTERNAL string = "EXTERNAL"
)

// prop value enum
func (m *RegisterDeviceResponse) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, registerDeviceResponseTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RegisterDeviceResponse) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegisterDeviceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterDeviceResponse) UnmarshalBinary(b []byte) error {
	var res RegisterDeviceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
