// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegisteredDevice registered device
//
// swagger:model RegisteredDevice
type RegisteredDevice struct {

	// ip
	IP string `json:"ip,omitempty"`

	// port
	Port string `json:"port,omitempty"`

	// user agent
	UserAgent string `json:"userAgent,omitempty"`
}

// Validate validates this registered device
func (m *RegisteredDevice) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisteredDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisteredDevice) UnmarshalBinary(b []byte) error {
	var res RegisteredDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
