// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResendFaxRequest resend fax request
//
// swagger:model ResendFaxRequest
type ResendFaxRequest struct {

	// fax Id
	// Required: true
	FaxID *string `json:"faxId"`

	// faxline Id
	FaxlineID string `json:"faxlineId,omitempty"`
}

// Validate validates this resend fax request
func (m *ResendFaxRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFaxID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResendFaxRequest) validateFaxID(formats strfmt.Registry) error {

	if err := validate.Required("faxId", "body", m.FaxID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResendFaxRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResendFaxRequest) UnmarshalBinary(b []byte) error {
	var res ResendFaxRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
