// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SetBusyOnBusySettingsRequest set busy on busy settings request
//
// swagger:model SetBusyOnBusySettingsRequest
type SetBusyOnBusySettingsRequest struct {

	// enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// Validate validates this set busy on busy settings request
func (m *SetBusyOnBusySettingsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetBusyOnBusySettingsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetBusyOnBusySettingsRequest) UnmarshalBinary(b []byte) error {
	var res SetBusyOnBusySettingsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
