// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetForwardingsRequest set forwardings request
//
// swagger:model SetForwardingsRequest
type SetForwardingsRequest struct {

	// forwardings
	// Max Items: 3
	// Min Items: 0
	Forwardings []*Forwarding `json:"forwardings"`
}

// Validate validates this set forwardings request
func (m *SetForwardingsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForwardings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetForwardingsRequest) validateForwardings(formats strfmt.Registry) error {

	if swag.IsZero(m.Forwardings) { // not required
		return nil
	}

	iForwardingsSize := int64(len(m.Forwardings))

	if err := validate.MinItems("forwardings", "body", iForwardingsSize, 0); err != nil {
		return err
	}

	if err := validate.MaxItems("forwardings", "body", iForwardingsSize, 3); err != nil {
		return err
	}

	for i := 0; i < len(m.Forwardings); i++ {
		if swag.IsZero(m.Forwardings[i]) { // not required
			continue
		}

		if m.Forwardings[i] != nil {
			if err := m.Forwardings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forwardings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SetForwardingsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetForwardingsRequest) UnmarshalBinary(b []byte) error {
	var res SetForwardingsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
