// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetSipgateIoPhonelineSettingsRequest set sipgate io phoneline settings request
//
// swagger:model SetSipgateIoPhonelineSettingsRequest
type SetSipgateIoPhonelineSettingsRequest struct {

	// allow self signed
	AllowSelfSigned *bool `json:"allowSelfSigned,omitempty"`

	// certificate
	Certificate string `json:"certificate,omitempty"`

	// incoming active
	IncomingActive *bool `json:"incomingActive,omitempty"`

	// incoming Url
	// Required: true
	IncomingURL *string `json:"incomingUrl"`

	// log
	Log *bool `json:"log,omitempty"`

	// outgoing active
	OutgoingActive *bool `json:"outgoingActive,omitempty"`

	// outgoing Url
	// Required: true
	OutgoingURL *string `json:"outgoingUrl"`
}

// Validate validates this set sipgate io phoneline settings request
func (m *SetSipgateIoPhonelineSettingsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIncomingURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutgoingURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetSipgateIoPhonelineSettingsRequest) validateIncomingURL(formats strfmt.Registry) error {

	if err := validate.Required("incomingUrl", "body", m.IncomingURL); err != nil {
		return err
	}

	return nil
}

func (m *SetSipgateIoPhonelineSettingsRequest) validateOutgoingURL(formats strfmt.Registry) error {

	if err := validate.Required("outgoingUrl", "body", m.OutgoingURL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SetSipgateIoPhonelineSettingsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetSipgateIoPhonelineSettingsRequest) UnmarshalBinary(b []byte) error {
	var res SetSipgateIoPhonelineSettingsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
