// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TariffAnnouncementRequest tariff announcement request
//
// swagger:model TariffAnnouncementRequest
type TariffAnnouncementRequest struct {

	// enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// Validate validates this tariff announcement request
func (m *TariffAnnouncementRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TariffAnnouncementRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TariffAnnouncementRequest) UnmarshalBinary(b []byte) error {
	var res TariffAnnouncementRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
