// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VerifySmsCallerIDRequest verify sms caller Id request
//
// swagger:model VerifySmsCallerIdRequest
type VerifySmsCallerIDRequest struct {

	// verification code
	VerificationCode string `json:"verificationCode,omitempty"`
}

// Validate validates this verify sms caller Id request
func (m *VerifySmsCallerIDRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifySmsCallerIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifySmsCallerIDRequest) UnmarshalBinary(b []byte) error {
	var res VerifySmsCallerIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
