// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewAddParallelForwardingParams creates a new AddParallelForwardingParams object
// with the default values initialized.
func NewAddParallelForwardingParams() *AddParallelForwardingParams {
	var ()
	return &AddParallelForwardingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddParallelForwardingParamsWithTimeout creates a new AddParallelForwardingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddParallelForwardingParamsWithTimeout(timeout time.Duration) *AddParallelForwardingParams {
	var ()
	return &AddParallelForwardingParams{

		timeout: timeout,
	}
}

// NewAddParallelForwardingParamsWithContext creates a new AddParallelForwardingParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddParallelForwardingParamsWithContext(ctx context.Context) *AddParallelForwardingParams {
	var ()
	return &AddParallelForwardingParams{

		Context: ctx,
	}
}

// NewAddParallelForwardingParamsWithHTTPClient creates a new AddParallelForwardingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddParallelForwardingParamsWithHTTPClient(client *http.Client) *AddParallelForwardingParams {
	var ()
	return &AddParallelForwardingParams{
		HTTPClient: client,
	}
}

/*AddParallelForwardingParams contains all the parameters to send to the API endpoint
for the add parallel forwarding operation typically these are written to a http.Request
*/
type AddParallelForwardingParams struct {

	/*Body*/
	Body *models.SetParallelForwardingRequest
	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithTimeout(timeout time.Duration) *AddParallelForwardingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithContext(ctx context.Context) *AddParallelForwardingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithHTTPClient(client *http.Client) *AddParallelForwardingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithBody(body *models.SetParallelForwardingRequest) *AddParallelForwardingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetBody(body *models.SetParallelForwardingRequest) {
	o.Body = body
}

// WithPhonelineID adds the phonelineID to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithPhonelineID(phonelineID string) *AddParallelForwardingParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the add parallel forwarding params
func (o *AddParallelForwardingParams) WithUserID(userID string) *AddParallelForwardingParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the add parallel forwarding params
func (o *AddParallelForwardingParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *AddParallelForwardingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
