// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeVoicemailSettingsReader is a Reader for the ChangeVoicemailSettings structure.
type ChangeVoicemailSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeVoicemailSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewChangeVoicemailSettingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewChangeVoicemailSettingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeVoicemailSettingsBadRequest creates a ChangeVoicemailSettingsBadRequest with default headers values
func NewChangeVoicemailSettingsBadRequest() *ChangeVoicemailSettingsBadRequest {
	return &ChangeVoicemailSettingsBadRequest{}
}

/*ChangeVoicemailSettingsBadRequest handles this case with default header values.

Voicemail settings could not be changed due to bad request
*/
type ChangeVoicemailSettingsBadRequest struct {
}

func (o *ChangeVoicemailSettingsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /{userId}/phonelines/{phonelineId}/voicemails/{voicemailId}][%d] changeVoicemailSettingsBadRequest ", 400)
}

func (o *ChangeVoicemailSettingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeVoicemailSettingsForbidden creates a ChangeVoicemailSettingsForbidden with default headers values
func NewChangeVoicemailSettingsForbidden() *ChangeVoicemailSettingsForbidden {
	return &ChangeVoicemailSettingsForbidden{}
}

/*ChangeVoicemailSettingsForbidden handles this case with default header values.

Transcription not available
*/
type ChangeVoicemailSettingsForbidden struct {
}

func (o *ChangeVoicemailSettingsForbidden) Error() string {
	return fmt.Sprintf("[PUT /{userId}/phonelines/{phonelineId}/voicemails/{voicemailId}][%d] changeVoicemailSettingsForbidden ", 403)
}

func (o *ChangeVoicemailSettingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
