// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewChangePhonelineVoicemailGreetingParams creates a new ChangePhonelineVoicemailGreetingParams object
// with the default values initialized.
func NewChangePhonelineVoicemailGreetingParams() *ChangePhonelineVoicemailGreetingParams {
	var ()
	return &ChangePhonelineVoicemailGreetingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangePhonelineVoicemailGreetingParamsWithTimeout creates a new ChangePhonelineVoicemailGreetingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangePhonelineVoicemailGreetingParamsWithTimeout(timeout time.Duration) *ChangePhonelineVoicemailGreetingParams {
	var ()
	return &ChangePhonelineVoicemailGreetingParams{

		timeout: timeout,
	}
}

// NewChangePhonelineVoicemailGreetingParamsWithContext creates a new ChangePhonelineVoicemailGreetingParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangePhonelineVoicemailGreetingParamsWithContext(ctx context.Context) *ChangePhonelineVoicemailGreetingParams {
	var ()
	return &ChangePhonelineVoicemailGreetingParams{

		Context: ctx,
	}
}

// NewChangePhonelineVoicemailGreetingParamsWithHTTPClient creates a new ChangePhonelineVoicemailGreetingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangePhonelineVoicemailGreetingParamsWithHTTPClient(client *http.Client) *ChangePhonelineVoicemailGreetingParams {
	var ()
	return &ChangePhonelineVoicemailGreetingParams{
		HTTPClient: client,
	}
}

/*ChangePhonelineVoicemailGreetingParams contains all the parameters to send to the API endpoint
for the change phoneline voicemail greeting operation typically these are written to a http.Request
*/
type ChangePhonelineVoicemailGreetingParams struct {

	/*Body*/
	Body *models.ChangeVoicemailGreetingRequest
	/*GreetingID
	  The unique greeting identifier

	*/
	GreetingID string
	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string
	/*VoicemailID
	  The unique voicemail identifier

	*/
	VoicemailID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithTimeout(timeout time.Duration) *ChangePhonelineVoicemailGreetingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithContext(ctx context.Context) *ChangePhonelineVoicemailGreetingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithHTTPClient(client *http.Client) *ChangePhonelineVoicemailGreetingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithBody(body *models.ChangeVoicemailGreetingRequest) *ChangePhonelineVoicemailGreetingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetBody(body *models.ChangeVoicemailGreetingRequest) {
	o.Body = body
}

// WithGreetingID adds the greetingID to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithGreetingID(greetingID string) *ChangePhonelineVoicemailGreetingParams {
	o.SetGreetingID(greetingID)
	return o
}

// SetGreetingID adds the greetingId to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetGreetingID(greetingID string) {
	o.GreetingID = greetingID
}

// WithPhonelineID adds the phonelineID to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithPhonelineID(phonelineID string) *ChangePhonelineVoicemailGreetingParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithUserID(userID string) *ChangePhonelineVoicemailGreetingParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetUserID(userID string) {
	o.UserID = userID
}

// WithVoicemailID adds the voicemailID to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) WithVoicemailID(voicemailID string) *ChangePhonelineVoicemailGreetingParams {
	o.SetVoicemailID(voicemailID)
	return o
}

// SetVoicemailID adds the voicemailId to the change phoneline voicemail greeting params
func (o *ChangePhonelineVoicemailGreetingParams) SetVoicemailID(voicemailID string) {
	o.VoicemailID = voicemailID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangePhonelineVoicemailGreetingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param greetingId
	if err := r.SetPathParam("greetingId", o.GreetingID); err != nil {
		return err
	}

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	// path param voicemailId
	if err := r.SetPathParam("voicemailId", o.VoicemailID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
