// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteParallelForwardingSettingsParams creates a new DeleteParallelForwardingSettingsParams object
// with the default values initialized.
func NewDeleteParallelForwardingSettingsParams() *DeleteParallelForwardingSettingsParams {
	var ()
	return &DeleteParallelForwardingSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteParallelForwardingSettingsParamsWithTimeout creates a new DeleteParallelForwardingSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteParallelForwardingSettingsParamsWithTimeout(timeout time.Duration) *DeleteParallelForwardingSettingsParams {
	var ()
	return &DeleteParallelForwardingSettingsParams{

		timeout: timeout,
	}
}

// NewDeleteParallelForwardingSettingsParamsWithContext creates a new DeleteParallelForwardingSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteParallelForwardingSettingsParamsWithContext(ctx context.Context) *DeleteParallelForwardingSettingsParams {
	var ()
	return &DeleteParallelForwardingSettingsParams{

		Context: ctx,
	}
}

// NewDeleteParallelForwardingSettingsParamsWithHTTPClient creates a new DeleteParallelForwardingSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteParallelForwardingSettingsParamsWithHTTPClient(client *http.Client) *DeleteParallelForwardingSettingsParams {
	var ()
	return &DeleteParallelForwardingSettingsParams{
		HTTPClient: client,
	}
}

/*DeleteParallelForwardingSettingsParams contains all the parameters to send to the API endpoint
for the delete parallel forwarding settings operation typically these are written to a http.Request
*/
type DeleteParallelForwardingSettingsParams struct {

	/*ParallelForwardingID
	  The unique external device identifier

	*/
	ParallelForwardingID string
	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithTimeout(timeout time.Duration) *DeleteParallelForwardingSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithContext(ctx context.Context) *DeleteParallelForwardingSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithHTTPClient(client *http.Client) *DeleteParallelForwardingSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParallelForwardingID adds the parallelForwardingID to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithParallelForwardingID(parallelForwardingID string) *DeleteParallelForwardingSettingsParams {
	o.SetParallelForwardingID(parallelForwardingID)
	return o
}

// SetParallelForwardingID adds the parallelForwardingId to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetParallelForwardingID(parallelForwardingID string) {
	o.ParallelForwardingID = parallelForwardingID
}

// WithPhonelineID adds the phonelineID to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithPhonelineID(phonelineID string) *DeleteParallelForwardingSettingsParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) WithUserID(userID string) *DeleteParallelForwardingSettingsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete parallel forwarding settings params
func (o *DeleteParallelForwardingSettingsParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteParallelForwardingSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param parallelForwardingId
	if err := r.SetPathParam("parallelForwardingId", o.ParallelForwardingID); err != nil {
		return err
	}

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
