// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDevicesForPhonelineParams creates a new GetDevicesForPhonelineParams object
// with the default values initialized.
func NewGetDevicesForPhonelineParams() *GetDevicesForPhonelineParams {
	var ()
	return &GetDevicesForPhonelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDevicesForPhonelineParamsWithTimeout creates a new GetDevicesForPhonelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDevicesForPhonelineParamsWithTimeout(timeout time.Duration) *GetDevicesForPhonelineParams {
	var ()
	return &GetDevicesForPhonelineParams{

		timeout: timeout,
	}
}

// NewGetDevicesForPhonelineParamsWithContext creates a new GetDevicesForPhonelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDevicesForPhonelineParamsWithContext(ctx context.Context) *GetDevicesForPhonelineParams {
	var ()
	return &GetDevicesForPhonelineParams{

		Context: ctx,
	}
}

// NewGetDevicesForPhonelineParamsWithHTTPClient creates a new GetDevicesForPhonelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDevicesForPhonelineParamsWithHTTPClient(client *http.Client) *GetDevicesForPhonelineParams {
	var ()
	return &GetDevicesForPhonelineParams{
		HTTPClient: client,
	}
}

/*GetDevicesForPhonelineParams contains all the parameters to send to the API endpoint
for the get devices for phoneline operation typically these are written to a http.Request
*/
type GetDevicesForPhonelineParams struct {

	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) WithTimeout(timeout time.Duration) *GetDevicesForPhonelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) WithContext(ctx context.Context) *GetDevicesForPhonelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) WithHTTPClient(client *http.Client) *GetDevicesForPhonelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhonelineID adds the phonelineID to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) WithPhonelineID(phonelineID string) *GetDevicesForPhonelineParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) WithUserID(userID string) *GetDevicesForPhonelineParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get devices for phoneline params
func (o *GetDevicesForPhonelineParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDevicesForPhonelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
