// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetPhonelinesReader is a Reader for the GetPhonelines structure.
type GetPhonelinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPhonelinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPhonelinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPhonelinesOK creates a GetPhonelinesOK with default headers values
func NewGetPhonelinesOK() *GetPhonelinesOK {
	return &GetPhonelinesOK{}
}

/*GetPhonelinesOK handles this case with default header values.

successful operation
*/
type GetPhonelinesOK struct {
	Payload *models.SimplePhonelinesResponse
}

func (o *GetPhonelinesOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/phonelines][%d] getPhonelinesOK  %+v", 200, o.Payload)
}

func (o *GetPhonelinesOK) GetPayload() *models.SimplePhonelinesResponse {
	return o.Payload
}

func (o *GetPhonelinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimplePhonelinesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
