// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPhonelineParams creates a new GetPhonelineParams object
// with the default values initialized.
func NewGetPhonelineParams() *GetPhonelineParams {
	var ()
	return &GetPhonelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPhonelineParamsWithTimeout creates a new GetPhonelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPhonelineParamsWithTimeout(timeout time.Duration) *GetPhonelineParams {
	var ()
	return &GetPhonelineParams{

		timeout: timeout,
	}
}

// NewGetPhonelineParamsWithContext creates a new GetPhonelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPhonelineParamsWithContext(ctx context.Context) *GetPhonelineParams {
	var ()
	return &GetPhonelineParams{

		Context: ctx,
	}
}

// NewGetPhonelineParamsWithHTTPClient creates a new GetPhonelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPhonelineParamsWithHTTPClient(client *http.Client) *GetPhonelineParams {
	var ()
	return &GetPhonelineParams{
		HTTPClient: client,
	}
}

/*GetPhonelineParams contains all the parameters to send to the API endpoint
for the get phoneline operation typically these are written to a http.Request
*/
type GetPhonelineParams struct {

	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get phoneline params
func (o *GetPhonelineParams) WithTimeout(timeout time.Duration) *GetPhonelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get phoneline params
func (o *GetPhonelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get phoneline params
func (o *GetPhonelineParams) WithContext(ctx context.Context) *GetPhonelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get phoneline params
func (o *GetPhonelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get phoneline params
func (o *GetPhonelineParams) WithHTTPClient(client *http.Client) *GetPhonelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get phoneline params
func (o *GetPhonelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhonelineID adds the phonelineID to the get phoneline params
func (o *GetPhonelineParams) WithPhonelineID(phonelineID string) *GetPhonelineParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the get phoneline params
func (o *GetPhonelineParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the get phoneline params
func (o *GetPhonelineParams) WithUserID(userID string) *GetPhonelineParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get phoneline params
func (o *GetPhonelineParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPhonelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
