// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPhonelinesParams creates a new GetPhonelinesParams object
// with the default values initialized.
func NewGetPhonelinesParams() *GetPhonelinesParams {
	var ()
	return &GetPhonelinesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPhonelinesParamsWithTimeout creates a new GetPhonelinesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPhonelinesParamsWithTimeout(timeout time.Duration) *GetPhonelinesParams {
	var ()
	return &GetPhonelinesParams{

		timeout: timeout,
	}
}

// NewGetPhonelinesParamsWithContext creates a new GetPhonelinesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPhonelinesParamsWithContext(ctx context.Context) *GetPhonelinesParams {
	var ()
	return &GetPhonelinesParams{

		Context: ctx,
	}
}

// NewGetPhonelinesParamsWithHTTPClient creates a new GetPhonelinesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPhonelinesParamsWithHTTPClient(client *http.Client) *GetPhonelinesParams {
	var ()
	return &GetPhonelinesParams{
		HTTPClient: client,
	}
}

/*GetPhonelinesParams contains all the parameters to send to the API endpoint
for the get phonelines operation typically these are written to a http.Request
*/
type GetPhonelinesParams struct {

	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get phonelines params
func (o *GetPhonelinesParams) WithTimeout(timeout time.Duration) *GetPhonelinesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get phonelines params
func (o *GetPhonelinesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get phonelines params
func (o *GetPhonelinesParams) WithContext(ctx context.Context) *GetPhonelinesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get phonelines params
func (o *GetPhonelinesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get phonelines params
func (o *GetPhonelinesParams) WithHTTPClient(client *http.Client) *GetPhonelinesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get phonelines params
func (o *GetPhonelinesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get phonelines params
func (o *GetPhonelinesParams) WithUserID(userID string) *GetPhonelinesParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get phonelines params
func (o *GetPhonelinesParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPhonelinesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
