// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPhonelineForwardingsParams creates a new GetPhonelineForwardingsParams object
// with the default values initialized.
func NewGetPhonelineForwardingsParams() *GetPhonelineForwardingsParams {
	var ()
	return &GetPhonelineForwardingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPhonelineForwardingsParamsWithTimeout creates a new GetPhonelineForwardingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPhonelineForwardingsParamsWithTimeout(timeout time.Duration) *GetPhonelineForwardingsParams {
	var ()
	return &GetPhonelineForwardingsParams{

		timeout: timeout,
	}
}

// NewGetPhonelineForwardingsParamsWithContext creates a new GetPhonelineForwardingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPhonelineForwardingsParamsWithContext(ctx context.Context) *GetPhonelineForwardingsParams {
	var ()
	return &GetPhonelineForwardingsParams{

		Context: ctx,
	}
}

// NewGetPhonelineForwardingsParamsWithHTTPClient creates a new GetPhonelineForwardingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPhonelineForwardingsParamsWithHTTPClient(client *http.Client) *GetPhonelineForwardingsParams {
	var ()
	return &GetPhonelineForwardingsParams{
		HTTPClient: client,
	}
}

/*GetPhonelineForwardingsParams contains all the parameters to send to the API endpoint
for the get phoneline forwardings operation typically these are written to a http.Request
*/
type GetPhonelineForwardingsParams struct {

	/*PhonelineID
	  The unique phone line identifier

	*/
	PhonelineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) WithTimeout(timeout time.Duration) *GetPhonelineForwardingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) WithContext(ctx context.Context) *GetPhonelineForwardingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) WithHTTPClient(client *http.Client) *GetPhonelineForwardingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhonelineID adds the phonelineID to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) WithPhonelineID(phonelineID string) *GetPhonelineForwardingsParams {
	o.SetPhonelineID(phonelineID)
	return o
}

// SetPhonelineID adds the phonelineId to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) SetPhonelineID(phonelineID string) {
	o.PhonelineID = phonelineID
}

// WithUserID adds the userID to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) WithUserID(userID string) *GetPhonelineForwardingsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get phoneline forwardings params
func (o *GetPhonelineForwardingsParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPhonelineForwardingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param phonelineId
	if err := r.SetPathParam("phonelineId", o.PhonelineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
