// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetSipgateIoLogsReader is a Reader for the GetSipgateIoLogs structure.
type GetSipgateIoLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSipgateIoLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSipgateIoLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetSipgateIoLogsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSipgateIoLogsOK creates a GetSipgateIoLogsOK with default headers values
func NewGetSipgateIoLogsOK() *GetSipgateIoLogsOK {
	return &GetSipgateIoLogsOK{}
}

/*GetSipgateIoLogsOK handles this case with default header values.

successful operation
*/
type GetSipgateIoLogsOK struct {
	Payload *models.PhonelineSipgateIoLogsResponse
}

func (o *GetSipgateIoLogsOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/phonelines/{phonelineId}/sipgateio/log][%d] getSipgateIoLogsOK  %+v", 200, o.Payload)
}

func (o *GetSipgateIoLogsOK) GetPayload() *models.PhonelineSipgateIoLogsResponse {
	return o.Payload
}

func (o *GetSipgateIoLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PhonelineSipgateIoLogsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSipgateIoLogsForbidden creates a GetSipgateIoLogsForbidden with default headers values
func NewGetSipgateIoLogsForbidden() *GetSipgateIoLogsForbidden {
	return &GetSipgateIoLogsForbidden{}
}

/*GetSipgateIoLogsForbidden handles this case with default header values.

sipgate.io feature not booked
*/
type GetSipgateIoLogsForbidden struct {
}

func (o *GetSipgateIoLogsForbidden) Error() string {
	return fmt.Sprintf("[GET /{userId}/phonelines/{phonelineId}/sipgateio/log][%d] getSipgateIoLogsForbidden ", 403)
}

func (o *GetSipgateIoLogsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
