// Code generated by go-swagger; DO NOT EDIT.

package phonelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetPhonelineAliasReader is a Reader for the SetPhonelineAlias structure.
type SetPhonelineAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPhonelineAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 404:
		result := NewSetPhonelineAliasNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPhonelineAliasNotFound creates a SetPhonelineAliasNotFound with default headers values
func NewSetPhonelineAliasNotFound() *SetPhonelineAliasNotFound {
	return &SetPhonelineAliasNotFound{}
}

/*SetPhonelineAliasNotFound handles this case with default header values.

Phoneline not found
*/
type SetPhonelineAliasNotFound struct {
}

func (o *SetPhonelineAliasNotFound) Error() string {
	return fmt.Sprintf("[PUT /{userId}/phonelines/{phonelineId}][%d] setPhonelineAliasNotFound ", 404)
}

func (o *SetPhonelineAliasNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
