// Code generated by go-swagger; DO NOT EDIT.

package faxlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewChangeTaglineParams creates a new ChangeTaglineParams object
// with the default values initialized.
func NewChangeTaglineParams() *ChangeTaglineParams {
	var ()
	return &ChangeTaglineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeTaglineParamsWithTimeout creates a new ChangeTaglineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeTaglineParamsWithTimeout(timeout time.Duration) *ChangeTaglineParams {
	var ()
	return &ChangeTaglineParams{

		timeout: timeout,
	}
}

// NewChangeTaglineParamsWithContext creates a new ChangeTaglineParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeTaglineParamsWithContext(ctx context.Context) *ChangeTaglineParams {
	var ()
	return &ChangeTaglineParams{

		Context: ctx,
	}
}

// NewChangeTaglineParamsWithHTTPClient creates a new ChangeTaglineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeTaglineParamsWithHTTPClient(client *http.Client) *ChangeTaglineParams {
	var ()
	return &ChangeTaglineParams{
		HTTPClient: client,
	}
}

/*ChangeTaglineParams contains all the parameters to send to the API endpoint
for the change tagline operation typically these are written to a http.Request
*/
type ChangeTaglineParams struct {

	/*Body*/
	Body *models.FaxlineTaglineRequest
	/*FaxlineID
	  The unique fax line identifier

	*/
	FaxlineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change tagline params
func (o *ChangeTaglineParams) WithTimeout(timeout time.Duration) *ChangeTaglineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change tagline params
func (o *ChangeTaglineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change tagline params
func (o *ChangeTaglineParams) WithContext(ctx context.Context) *ChangeTaglineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change tagline params
func (o *ChangeTaglineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change tagline params
func (o *ChangeTaglineParams) WithHTTPClient(client *http.Client) *ChangeTaglineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change tagline params
func (o *ChangeTaglineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change tagline params
func (o *ChangeTaglineParams) WithBody(body *models.FaxlineTaglineRequest) *ChangeTaglineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change tagline params
func (o *ChangeTaglineParams) SetBody(body *models.FaxlineTaglineRequest) {
	o.Body = body
}

// WithFaxlineID adds the faxlineID to the change tagline params
func (o *ChangeTaglineParams) WithFaxlineID(faxlineID string) *ChangeTaglineParams {
	o.SetFaxlineID(faxlineID)
	return o
}

// SetFaxlineID adds the faxlineId to the change tagline params
func (o *ChangeTaglineParams) SetFaxlineID(faxlineID string) {
	o.FaxlineID = faxlineID
}

// WithUserID adds the userID to the change tagline params
func (o *ChangeTaglineParams) WithUserID(userID string) *ChangeTaglineParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the change tagline params
func (o *ChangeTaglineParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeTaglineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param faxlineId
	if err := r.SetPathParam("faxlineId", o.FaxlineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
