// Code generated by go-swagger; DO NOT EDIT.

package faxlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// NewChangeFaxlineCallerIDSettingsParams creates a new ChangeFaxlineCallerIDSettingsParams object
// with the default values initialized.
func NewChangeFaxlineCallerIDSettingsParams() *ChangeFaxlineCallerIDSettingsParams {
	var ()
	return &ChangeFaxlineCallerIDSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeFaxlineCallerIDSettingsParamsWithTimeout creates a new ChangeFaxlineCallerIDSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeFaxlineCallerIDSettingsParamsWithTimeout(timeout time.Duration) *ChangeFaxlineCallerIDSettingsParams {
	var ()
	return &ChangeFaxlineCallerIDSettingsParams{

		timeout: timeout,
	}
}

// NewChangeFaxlineCallerIDSettingsParamsWithContext creates a new ChangeFaxlineCallerIDSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeFaxlineCallerIDSettingsParamsWithContext(ctx context.Context) *ChangeFaxlineCallerIDSettingsParams {
	var ()
	return &ChangeFaxlineCallerIDSettingsParams{

		Context: ctx,
	}
}

// NewChangeFaxlineCallerIDSettingsParamsWithHTTPClient creates a new ChangeFaxlineCallerIDSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeFaxlineCallerIDSettingsParamsWithHTTPClient(client *http.Client) *ChangeFaxlineCallerIDSettingsParams {
	var ()
	return &ChangeFaxlineCallerIDSettingsParams{
		HTTPClient: client,
	}
}

/*ChangeFaxlineCallerIDSettingsParams contains all the parameters to send to the API endpoint
for the change faxline caller Id settings operation typically these are written to a http.Request
*/
type ChangeFaxlineCallerIDSettingsParams struct {

	/*Body*/
	Body *models.FaxlineCallerIDRequest
	/*FaxlineID
	  The unique fax line identifier

	*/
	FaxlineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithTimeout(timeout time.Duration) *ChangeFaxlineCallerIDSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithContext(ctx context.Context) *ChangeFaxlineCallerIDSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithHTTPClient(client *http.Client) *ChangeFaxlineCallerIDSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithBody(body *models.FaxlineCallerIDRequest) *ChangeFaxlineCallerIDSettingsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetBody(body *models.FaxlineCallerIDRequest) {
	o.Body = body
}

// WithFaxlineID adds the faxlineID to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithFaxlineID(faxlineID string) *ChangeFaxlineCallerIDSettingsParams {
	o.SetFaxlineID(faxlineID)
	return o
}

// SetFaxlineID adds the faxlineId to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetFaxlineID(faxlineID string) {
	o.FaxlineID = faxlineID
}

// WithUserID adds the userID to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) WithUserID(userID string) *ChangeFaxlineCallerIDSettingsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the change faxline caller Id settings params
func (o *ChangeFaxlineCallerIDSettingsParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeFaxlineCallerIDSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param faxlineId
	if err := r.SetPathParam("faxlineId", o.FaxlineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
