// Code generated by go-swagger; DO NOT EDIT.

package faxlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFaxlineNumbersParams creates a new GetFaxlineNumbersParams object
// with the default values initialized.
func NewGetFaxlineNumbersParams() *GetFaxlineNumbersParams {
	var ()
	return &GetFaxlineNumbersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFaxlineNumbersParamsWithTimeout creates a new GetFaxlineNumbersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFaxlineNumbersParamsWithTimeout(timeout time.Duration) *GetFaxlineNumbersParams {
	var ()
	return &GetFaxlineNumbersParams{

		timeout: timeout,
	}
}

// NewGetFaxlineNumbersParamsWithContext creates a new GetFaxlineNumbersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFaxlineNumbersParamsWithContext(ctx context.Context) *GetFaxlineNumbersParams {
	var ()
	return &GetFaxlineNumbersParams{

		Context: ctx,
	}
}

// NewGetFaxlineNumbersParamsWithHTTPClient creates a new GetFaxlineNumbersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFaxlineNumbersParamsWithHTTPClient(client *http.Client) *GetFaxlineNumbersParams {
	var ()
	return &GetFaxlineNumbersParams{
		HTTPClient: client,
	}
}

/*GetFaxlineNumbersParams contains all the parameters to send to the API endpoint
for the get faxline numbers operation typically these are written to a http.Request
*/
type GetFaxlineNumbersParams struct {

	/*FaxlineID
	  The unique fax line identifier

	*/
	FaxlineID string
	/*UserID
	  The unique user identifier

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get faxline numbers params
func (o *GetFaxlineNumbersParams) WithTimeout(timeout time.Duration) *GetFaxlineNumbersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get faxline numbers params
func (o *GetFaxlineNumbersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get faxline numbers params
func (o *GetFaxlineNumbersParams) WithContext(ctx context.Context) *GetFaxlineNumbersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get faxline numbers params
func (o *GetFaxlineNumbersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get faxline numbers params
func (o *GetFaxlineNumbersParams) WithHTTPClient(client *http.Client) *GetFaxlineNumbersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get faxline numbers params
func (o *GetFaxlineNumbersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFaxlineID adds the faxlineID to the get faxline numbers params
func (o *GetFaxlineNumbersParams) WithFaxlineID(faxlineID string) *GetFaxlineNumbersParams {
	o.SetFaxlineID(faxlineID)
	return o
}

// SetFaxlineID adds the faxlineId to the get faxline numbers params
func (o *GetFaxlineNumbersParams) SetFaxlineID(faxlineID string) {
	o.FaxlineID = faxlineID
}

// WithUserID adds the userID to the get faxline numbers params
func (o *GetFaxlineNumbersParams) WithUserID(userID string) *GetFaxlineNumbersParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get faxline numbers params
func (o *GetFaxlineNumbersParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFaxlineNumbersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param faxlineId
	if err := r.SetPathParam("faxlineId", o.FaxlineID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
