// Code generated by go-swagger; DO NOT EDIT.

package faxlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/sipgate-rest-api/models"
)

// GetUserFaxlinesReader is a Reader for the GetUserFaxlines structure.
type GetUserFaxlinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserFaxlinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserFaxlinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetUserFaxlinesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserFaxlinesOK creates a GetUserFaxlinesOK with default headers values
func NewGetUserFaxlinesOK() *GetUserFaxlinesOK {
	return &GetUserFaxlinesOK{}
}

/*GetUserFaxlinesOK handles this case with default header values.

successful operation
*/
type GetUserFaxlinesOK struct {
	Payload *models.FaxlinesResponse
}

func (o *GetUserFaxlinesOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/faxlines][%d] getUserFaxlinesOK  %+v", 200, o.Payload)
}

func (o *GetUserFaxlinesOK) GetPayload() *models.FaxlinesResponse {
	return o.Payload
}

func (o *GetUserFaxlinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FaxlinesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserFaxlinesForbidden creates a GetUserFaxlinesForbidden with default headers values
func NewGetUserFaxlinesForbidden() *GetUserFaxlinesForbidden {
	return &GetUserFaxlinesForbidden{}
}

/*GetUserFaxlinesForbidden handles this case with default header values.

Feature not booked
*/
type GetUserFaxlinesForbidden struct {
}

func (o *GetUserFaxlinesForbidden) Error() string {
	return fmt.Sprintf("[GET /{userId}/faxlines][%d] getUserFaxlinesForbidden ", 403)
}

func (o *GetUserFaxlinesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
